ios/Podfile.lock, package.json, src/components/modal/pin/PinModal.tsx, src/navigation/intro/screens/Shop.tsx, src/navigation/tabs/home/HomeRoot.tsx, src/navigation/tabs/home/components/KeyMigrationFailureModal.tsx, src/navigation/wallet/screens/KeyOverview.tsx, src/store/app/app.actions.ts, src/store/app/app.effects.ts, src/store/app/app.reducer.ts, src/store/app/app.types.ts, src/store/coinbase/coinbase.effects.ts, src/store/wallet/effects/import/import.ts, src/store/wallet/effects/init/init.ts, src/store/wallet/effects/status/status.ts, src/store/wallet/utils/wallet.ts, yarn.lock
=> [FEAT] app migration

src/navigation/tabs/shop/components/GiftCardCatalog.tsx, src/navigation/tabs/shop/gift-card/screens/BuyGiftCard.tsx
Fix gift card catalog scroll position on search input focus when user has not purchased any gift cards.
=> Fix zero-state gift card scroll position on search input focus

src/navigation/tabs/home/HomeRoot.tsx, src/navigation/tabs/home/components/Crypto.tsx, src/navigation/tabs/settings/components/WalletsAndKeys.tsx, src/utils/hooks/useRequireKeyAndWalletRedirect.ts
Migrated encrypted keys are causing crashes when trying to grab mnemonic for backup. This PR adds the decrypt modal prior to navigating.
=> [FIX] decrypt before backup

src/components/modal/pin/PinModal.tsx, src/navigation/coinbase/components/CoinbaseBalanceCard.tsx, src/navigation/coinbase/components/CoinbaseDashboard.tsx, src/navigation/coinbase/screens/CoinbaseAccount.tsx, src/navigation/coinbase/screens/CoinbaseTransaction.tsx, src/navigation/onboarding/screens/Pin.tsx, src/navigation/onboarding/screens/TermsOfUse.tsx, src/navigation/wallet/screens/KeyOverview.tsx, src/navigation/wallet/screens/KeySettings.tsx
- Coinbase currency code
- Coinbase transaction details header sent/received icon position
- key overview -> encrypt password -> create password back button [does navigate back to key settings]
- update onboarding terms underline color
- Delete key
- onboarding -> pin screen -> select pin -> back button on pin screen takes to create wallet instead of going back to pin screen
=> minor bug fixes

src/components/modal/bottom-notification/BottomNotification.tsx, src/components/styled/Containers.tsx, src/navigation/bitpay-id/screens/ProfileSettings.tsx, src/navigation/tabs/shop/ShopStack.tsx, src/navigation/tabs/shop/components/FilterSheet.tsx, src/navigation/tabs/shop/components/GiftCardDiscountText.tsx, src/navigation/tabs/shop/components/MerchantItem.tsx, src/navigation/tabs/shop/components/MyGiftCards.tsx, src/navigation/tabs/shop/components/ShopDiscountText.tsx, src/navigation/tabs/shop/components/ShopOnline.tsx, src/navigation/tabs/shop/components/styled/ShopTabComponents.tsx, src/navigation/tabs/shop/gift-card/GiftCardStack.tsx, src/navigation/tabs/shop/gift-card/screens/ArchivedGiftCards.tsx, src/navigation/tabs/shop/gift-card/screens/BuyGiftCard.tsx, src/navigation/tabs/shop/gift-card/screens/GiftCardDetails.tsx, src/navigation/tabs/shop/merchant/screens/MerchantDetails.tsx, src/store/bitpay-id/bitpay-id.actions.ts, src/store/bitpay-id/bitpay-id.models.ts, src/store/bitpay-id/bitpay-id.reducer.ts, src/store/shop/shop.actions.ts, src/store/shop/shop.effects.ts, src/store/shop/shop.reducer.ts, src/store/shop/shop.types.ts
1. make redeem instructions and category filter sheets scrollable
2. use FlatList for archived gift cards screen to boost performance
3. fix react-native style warning on gift card details page
4. ensure promos on shop online merchants don’t overlap with long descriptions 
5. ensure shop online merchants can handle all discount types
6. ensure swiping back from gift card details in archived view goes back to the previous screen rather than removing the whole stack
7. ensure headerTitle styling is consistent across all shop tab screens
=> Misc shop tab fixes and improvements

src/navigation/tabs/shop/components/GiftCardCatalog.tsx, src/navigation/tabs/shop/components/GiftCardItem.tsx, src/store/bitpay-id/bitpay-id.actions.ts, src/store/bitpay-id/bitpay-id.types.ts
Fixes an issue that results in a newly purchased gift card not appearing on the shop tab after a user's first ever gift card purchase (until the app is relaunched).
Also removes some no longer needed code.
=> Fix first gift card purchase not appearing on the shop tab

android/app/src/main/res/xml/network_security_config.xml
=> Fix debug flag

src/components/list/WalletSettingsRow.tsx, src/navigation/wallet/screens/KeySettings.tsx
* Smaller icons
* Size adjustment "Add Wallet"
=> Ref: minor fix to match design

assets/img/slide-arrow.svg, src/components/swipe-button/SwipeButton.tsx, src/navigation/wallet/screens/send/confirm/DebitCardConfirm.tsx, src/navigation/wallet/screens/send/confirm/PayProConfirm.tsx, src/navigation/wallet/screens/send/confirm/Shared.tsx
1. Add expiration timer to PayPro Confirm Screen
2. Add memo to PayPro Confirm Screen
3. Add arrow to Slide to Send button
=> Confirm Screen Improvements

src/Root.tsx, src/store/app/app.effects.ts, src/store/wallet/utils/wallet.ts
Updates balance/etc when receive silent push notifications
=> Feat (RN-455): events handler

src/navigation/wallet/screens/Amount.tsx
=> Fix: keyboard view for small screen

src/components/modal/bottom-notification/BottomNotification.tsx
=> Fix: removed ScrollView to avoid nested VirtualizedList

src/navigation/tabs/shop/components/PhoneCountryModal.tsx, src/navigation/tabs/shop/gift-card/screens/ArchivedGiftCards.tsx, src/navigation/tabs/shop/gift-card/screens/EnterPhone.tsx
1. Fixes phone country modal close button that was rendered slightly cut-off and did not respond to presses
2. Uses FlatList to render country list
3. The country code prefix within the phone input now dynamically adjusts in width to better accommodate really long phone country codes
4. Fixes imports and typescript errors in ArchivedGiftCards.tsx
=> Phone country selector improvements

src/navigation/tabs/settings/SettingsRoot.tsx
https://user-images.githubusercontent.com/237435/176200879-c1d068d4-1b78-453f-9f95-a53298c4408c.mov
=> Feat: adds simple animation to the Settings dropdown

src/Root.tsx, src/navigation/tabs/shop/ShopStack.tsx, src/navigation/tabs/shop/gift-card/GiftCardStack.tsx, src/navigation/wallet/WalletStack.tsx
And remove no longer used code
=> Prevent swipe to go back on gift card confirm screen

src/navigation/coinbase/components/CoinbaseBalanceCard.tsx, src/navigation/wallet/screens/KeyOverview.tsx, src/navigation/wallet/screens/WalletDetails.tsx
* Also adds required params to Coinbase Balance Card
=> Ref: remove unused functions

src/navigation/tabs/home/components/Crypto.tsx
=> Fix: show Coinbase in Home although no key was created/imported

src/navigation/wallet/components/FileOrText.tsx, src/navigation/wallet/components/RecoveryPhrase.tsx
Related to: https://github.com/bitpay/bitpay-app/pull/181
=> Fix: avoid keyboard open above the recovery phrase input

src/navigation/wallet/screens/KeyOverview.tsx, src/navigation/wallet/screens/WalletDetails.tsx
Events requested by the product team
=> Feat: "View Key/Wallet" segment events

src/navigation/wallet/screens/TransactionProposalNotifications.tsx, src/store/wallet/effects/send/send.ts
=> [FIX] return signedTx if not yet broadcasted

src/navigation/wallet/screens/GlobalSelect.tsx
Fix:
* Sending from contacts
* Sending from BIP21 URI
=> Fix: error sending

src/navigation/wallet/components/RecoveryPhrase.tsx
=> import phrase: Turn off auto correct

src/store/log/log.actions.ts
=> dev: log loggers for devs

src/navigation/wallet/screens/RecoveryPhrase.tsx
=> Fix: "snapToItem of null" rejection when backup is canceled

src/navigation/tabs/settings/notifications/screens/PushNotifications.tsx
=> [RN-572]: fix notification view UI

src/navigation/tabs/settings/about/screens/SessionLog.tsx
=> Ref: Session Logs screen. Moved button to top right. Fix font size/weight

src/navigation/services/swap-crypto/components/WalletSelectorModal.tsx, src/navigation/services/swap-crypto/screens/ChangellyCheckout.tsx, src/navigation/services/swap-crypto/screens/SwapCryptoRoot.tsx, src/navigation/services/swap-crypto/styled/SwapCryptoRoot.styled.tsx, src/navigation/wallet/screens/GlobalSelect.tsx
This PR also fixes the wallet selector to allow the swaps of tokens not supported by bitpay
=> Feat: wallet selector improvements in swap crypto

src/navigation/tabs/settings/notifications/screens/EmailNotifications.tsx, src/navigation/wallet/screens/DeleteKey.tsx, src/store/app/app.effects.ts, src/store/wallet/effects/create-multisig/create-multisig.ts, src/store/wallet/effects/create/create.ts, src/store/wallet/effects/import/import.ts, src/store/wallet/effects/join-multisig/join-multisig.ts
* Fix: Unsubscribe email notifications from Settings
* Subscribe new created/imported wallets to email notifications if enabled
* Unsubscribe push/email notification when key is deleted
=> Fix: email notifications

src/navigation/tabs/home/components/Crypto.tsx, src/navigation/wallet/components/RequestEncryptPasswordToggle.tsx, src/navigation/wallet/screens/Backup.tsx, src/navigation/wallet/screens/CreateEncryptionPassword.tsx, src/navigation/wallet/screens/KeyOverview.tsx, src/navigation/wallet/screens/KeySettings.tsx, src/navigation/wallet/screens/TransactionProposalDetails.tsx, src/navigation/wallet/screens/TransactionProposalNotifications.tsx, src/navigation/wallet/screens/WalletSettings.tsx, src/store/transforms/transforms.ts, src/store/wallet-connect/wallet-connect.effects.ts, src/store/wallet/effects/create-multisig/create-multisig.ts, src/store/wallet/effects/create/create.ts, src/store/wallet/effects/import/import.ts, src/store/wallet/effects/join-multisig/join-multisig.ts, src/store/wallet/effects/send/send.ts, src/store/wallet/effects/status/status.ts, src/store/wallet/effects/transactions/transactions.ts, src/store/wallet/utils/wallet.ts, src/store/wallet/wallet.models.ts, src/store/wallet/wallet.reducer.ts, src/utils/helper-methods.ts
For testing :
pass: 1
{"iv":"TU65PeZQ2uA/PsUi6nX/4A==","v":1,"iter":10000,"ks":128,"ts":64,"mode":"ccm","adata":"","cipher":"aes","salt":"ct+AlsEv8/s=","ct":"P+xwSWllFrMS7gw56m6LqOCaumU/SQWuqRB79XusD4B/UG9cXibGuILA840mMdDOGQ7QIRjxl3ENsYabDmdJXkK98HFpCcqsfmQijVTThKBKB+AV1DyzEsGkE/ohjUBG0AFvViJgKyYdP5aLi0esO6cYgPisg9tNzsw18tBIEL7LJjsflVVcGgkrxRyRk0BvN8P9Clo08DgovcwpR66d++oJvaEdkMa4FYfYhtvQu+fdDpHlQ5kJGgRwIJcgPXoE8WgR3LIjrtkFVyAM/SClu85UN0mj2jGvHEHFoWZ+DqCpshK7U8plRGEPS2A/tNUHlSnuF/iATvm4rIebSKvSFdOTuib1Nh543DvhrA9rooiCy6JMwbdbaITTd1DDcpVRlMtTpnjyOn3Np5/hI8aDQLwmzZrI3PY3bL9MO1uPEHYhFkitu1b+lc/bWMcoK+ttwQUMPFI9czmaT1tUvTRRvoJ3HeC0crvQe64fxwS68dbAq9CuOcTRA7C9tJMvSoBe/YtYNHkU+PVGmyzpOa3+c5SPqZr2vmyTBLvlpjGUy2jJGO/vjYwfQQw9mGgfmbM6uDiEQmJeJzRQuGvDEnllp/CfUFbUaAYIk/t8ZwrF1fNr6uh+64LVNPe6nNxikk/W+T …
=> [FEAT] read only support

src/navigation/auth/components/AuthFormContainer.tsx
=> [FIX] wrap checkbox text

src/constants/wallet.ts, src/store/log/log.actions.ts, src/store/wallet/effects/rates/rates.ts
Increase time for rates cached from 10 seconds to 5 minutes.
=> Ref: increase time for rates cached. Improve error messages

src/navigation/wallet/screens/TransactionDetails.tsx
=> Fix: typo "confirmations" number in tx details

src/navigation/wallet/screens/send/TransactionLevel.tsx
=> Fix: keyboard overlaps the custom network fee field

src/navigation/tabs/home/components/Crypto.tsx, src/navigation/tabs/home/components/HomeSection.tsx, src/navigation/tabs/home/components/advertisements/AdvertisementsList.tsx, src/navigation/tabs/home/components/exchange-rates/ExchangeRatesList.tsx, src/navigation/tabs/home/components/offers/OffersCarousel.tsx, src/navigation/tabs/home/components/quick-links/QuickLinksCarousel.tsx
=> Fix: adjust margin and spacing of titles. Support for long words.

src/navigation/wallet/screens/TransactionProposalNotifications.tsx, src/store/wallet/effects/send/send.ts
Do not show sign checkbox from already accepted txps
=> [REF] dont remove txp if err - hide checkbox from already signed txp

src/Root.tsx, src/navigation/tabs/home/components/cards/CarouselKeySkeleton.tsx, src/navigation/tabs/home/components/cards/ListKeySkeleton.tsx, src/navigation/wallet/components/RecoveryPhrase.tsx, src/store/app/app.effects.ts, src/store/wallet/effects/import/import.ts
=> Deferred key import improvements

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/bitpay/wallet/LaunchActivity.java, android/app/src/main/java/com/bitpay/wallet/MainActivity.java, android/app/src/main/java/com/bitpay/wallet/MainApplication.java
Solution: 
https://github.com/proyecto26/react-native-inappbrowser/issues/213 
Note:
No changes on Android Mode: SingleTask.
Needs review:
* Check if deeplink works when click inside IAB
Steps to reproduce:
1- Go to Tab Card. Click on Sign up
2- Go to Home (Android)
3- Click on the icon app (no click from list of opened apps)
=> Fix: browser closing when app sent to background

locales/de/translation.json, locales/en/translation.json, locales/es/translation.json, locales/fr/translation.json, locales/ja/translation.json, locales/nl/translation.json, locales/pt/translation.json, locales/ru/translation.json, locales/zh/translation.json, package.json, src/constants/currencies.ts, src/constants/tokens.ts, src/navigation/services/buy-crypto/utils/simplex-utils.ts, src/navigation/services/buy-crypto/utils/wyre-utils.ts, src/navigation/wallet/screens/AddingOptions.tsx, src/navigation/wallet/screens/CreationOptions.tsx, src/navigation/wallet/screens/CurrencySelection.tsx, src/navigation/wallet/screens/send/SendTo.tsx, src/store/wallet/effects/paypro/paypro.ts, src/store/wallet/effects/send/send.ts, src/store/wallet/utils/wallet.ts, yarn.lock
Fixes: 
- paying invoices is not possible right now
- show correct name and symbol when creating a wallet
- Rate not found for currency: usdp
- possible duplicated key error if wrong pax wallet is created
=> [REF] rename from pax to usdp

src/navigation/services/swap-crypto/screens/ChangellyCheckout.tsx, src/store/wallet/effects/send/send.ts
Changes on BWC are required for creating ERC20 and ETH multisig transaction: https://github.com/bitpay/bitcore/pull/3440
* Also update link to new model "Rate".
=> Fix: update chain name for new BWC: ETHERC20

src/navigation/tabs/settings/general/screens/LanguageSettings.tsx
https://user-images.githubusercontent.com/237435/191552134-302226c9-a881-4ae0-bdef-3c4f209991ff.mp4
=> Ref: adds ActivityIndicator to avoid delay when setting language

src/navigation/bitpay-id/screens/ReceiveSettings.tsx, src/navigation/bitpay-id/utils/bitpay-id-utils.ts, src/navigation/wallet/screens/send/confirm/Shared.tsx, src/store/bitpay-id/bitpay-id.effects.ts, src/store/bitpay-id/bitpay-id.models.ts, src/store/wallet/utils/currency.ts
Some recently merged matic related changes broke the receive settings screen. This PR fixes the crashes and gets receive settings working again.
=> Fix Receive Settings

src/navigation/tabs/settings/components/Crypto.tsx, src/navigation/tabs/settings/screens/NewtorkFeePolicy.tsx, src/navigation/wallet/screens/WalletDetails.tsx, src/store/wallet/effects/fee/fee.ts, src/store/wallet/effects/send/send.ts
also fix update tx on confirm page
=> [FEAT]: allow edit matic nonce

src/navigation/wallet-connect/components/Connections.tsx, src/navigation/wallet-connect/components/WalletSelector.tsx, src/navigation/wallet-connect/screens/WalletConnectHome.tsx, src/navigation/wallet-connect/screens/WalletConnectStart.tsx, src/store/wallet-connect/wallet-connect.effects.ts
It needs https://github.com/bitpay/bitpay-app/pull/427
=> WalletConnect Polygon support

src/store/scan/scan.effects.ts
=> Fix ts error - make email param optional in goToConfirm params

src/components/amount/AmountModal.tsx, src/store/wallet/utils/wallet.ts
=> Fix: Coinbase. Show correct badge for matic (ETH network)

src/navigation/bitpay-id/screens/EnableTwoFactor.tsx, src/navigation/wallet/screens/send/SendTo.tsx
Also makes email search only possible for logged in users for now.
=> Fix value copied to clipboard when tapping qr code for enabling 2fa

android/app/src/main/AndroidManifest.xml, ios/BitPayApp/Info.plist, package.json, src/constants/config.ts, src/navigation/tabs/contacts/screens/ContactsAdd.tsx, src/navigation/wallet/screens/send/SendTo.tsx, src/store/scan/scan.effects.ts, src/store/wallet/effects/paypro/paypro.ts, src/store/wallet/effects/send/send.ts, src/store/wallet/utils/decode-uri.ts, src/store/wallet/utils/validations.ts, src/store/wallet/utils/wallet.ts, yarn.lock
needs: https://github.com/bitpay/bitcore/pull/3459
=> [FEAT] Matic Invoice - BIP21 URI

src/api/coinbase/coinbase.types.ts, src/navigation/coinbase/screens/CoinbaseAccount.tsx, src/navigation/wallet/screens/GlobalSelect.tsx, src/store/wallet/utils/wallet.ts
=> Ref: support matic deposit/withdrawal (Coinbase)

src/components/list/WalletRow.tsx
=> [FIX]: UI fix for large balances

src/navigation/tabs/home/HomeRoot.tsx, src/navigation/wallet/screens/KeyOverview.tsx, src/navigation/wallet/screens/TransactionProposalDetails.tsx, src/navigation/wallet/screens/TransactionProposalNotifications.tsx, src/navigation/wallet/screens/WalletDetails.tsx
TODO: check that are filtered on proposals notifications view
=> [FIX] hide txp label for 1-1 - msg for failed invoice payments

src/store/transforms/transforms.ts, src/store/wallet/utils/wallet.ts
=> Fix: icons for custom tokens

src/navigation/wallet/screens/AddWallet.tsx, src/navigation/wallet/screens/send/SendTo.tsx, src/store/bitpay-id/bitpay-id.effects.ts
=> Enable sending to an email address for users who are not logged in

src/components/list/WalletSettingsRow.tsx, src/navigation/wallet/screens/KeySettings.tsx
=> [FEAT] add badge icon to wallets settings list

src/navigation/wallet/components/MultipleOutputsTx.tsx, src/store/wallet/effects/transactions/transactions.ts
=> Revert "[FIX] get contact name function"

src/components/list/WalletRow.tsx, src/navigation/wallet/components/SendToAddress.tsx, src/navigation/wallet/screens/TransactionDetails.tsx, src/navigation/wallet/screens/send/SendTo.tsx
=> Fix: show compatible wallets on Multiple Recipients Screen

src/navigation/tabs/contacts/screens/ContactsAdd.tsx, src/navigation/wallet/components/MultipleOutputsTx.tsx, src/navigation/wallet/components/SendToPill.tsx, src/navigation/wallet/screens/TransactionDetails.tsx
And pass that email into the "Add contact" screen
=> Show recipient email in transaction details

src/navigation/tabs/home/components/advertisements/AdvertisementCard.tsx, src/navigation/tabs/home/components/offers/OfferCard.tsx, src/store/app/app.effects.ts, src/store/shop/shop.selectors.ts, src/utils/hooks/useDeeplinks.ts
The following deep link will now work: `bitpay://shoponline?category=charities%20%26%20nonprofits`
=> Implement deep link to shop online category screen

src/navigation/tabs/shop/ShopStack.tsx, src/navigation/tabs/shop/components/MyGiftCards.tsx, src/navigation/tabs/shop/gift-card/screens/ArchivedGiftCards.tsx
Improves performance of gift card config retrieval by searching a map rather than a list, and prevents a potential crash on the archived gift cards screen in cases when a gift card has no corresponding config.
=> Improve gift card config management

src/navigation/wallet/screens/AddWallet.tsx
https://user-images.githubusercontent.com/237435/203146566-797c20f5-c861-4386-8796-92deec628f91.mov
=> Fix: Go back to KeyOverview after add a Wallet (WalletDetails)

src/navigation/card/components/CardIntroFeatureTabs.tsx
=> [RN-776]: fix for card load description padding

src/navigation/coinbase/components/CoinbaseBalanceCard.tsx, src/navigation/coinbase/components/CoinbaseDashboard.tsx, src/navigation/tabs/home/components/Wallet.tsx, src/navigation/wallet/components/CoinbaseDropdownOption.tsx, src/navigation/wallet/components/KeyDropdownOption.tsx, src/navigation/wallet/screens/KeyOverview.tsx
=> [RN-771]: Coinbase added to key selector

src/navigation/wallet/screens/CurrencySelection.tsx
=> [RN-532]: add custom token option

src/navigation/wallet/components/FileOrText.tsx, src/navigation/wallet/components/RecoveryPhrase.tsx, src/navigation/wallet/screens/AddWallet.tsx, src/navigation/wallet/screens/DeleteKey.tsx, src/navigation/wallet/screens/WalletSettings.tsx, src/store/wallet/effects/import/import.ts
* Adds sleep function to avoid refresh with old data
Tests with funds:
* Delete key
* Import key
* Hide wallet with funds
=> Fix: refresh total balance when add/rm/hide assets

src/store/app/app.effects.ts, src/store/bitpay-id/bitpay-id.effects.ts
Decreases the time it takes to launch the app and prevents unnecessary launch delays by no longer awaiting async processes that are not critical to launch the app.
=> Improve app launch speed

src/navigation/coinbase/screens/CoinbaseAccount.tsx, src/store/wallet/effects/transactions/transactions.ts, src/store/wallet/utils/time.ts
=> FEAT [RN-787]: group Coinbase txs by month and show pendings

src/navigation/wallet/screens/send/confirm/Confirm.tsx, src/navigation/wallet/screens/send/confirm/Shared.tsx
=> Ref [RN-250] show flag [Testnet] on Confirm screen for testnet wallets

src/components/list/WalletRow.tsx, src/components/styled/Text.tsx
based on https://github.com/bitpay/bitpay-app/pull/661
=> Fix: Badge alignment

src/Root.tsx, src/components/list/WalletRow.tsx, src/navigation/tabs/settings/NetworkFeePolicy/NetworkFeePolicyStack.tsx, src/navigation/tabs/settings/NetworkFeePolicy/screens/NewtorkFeePolicy.tsx, src/navigation/tabs/settings/SettingsStack.tsx, src/navigation/tabs/settings/components/Crypto.tsx
the tab bar should not be visible
=> [RN-849]: Network fee policies navigation

src/navigation/tabs/home/HomeRoot.tsx
This PR removes some leftover code from a bad merge.
=> Fix bad merge

src/navigation/services/swap-crypto/screens/ChangellyCheckout.tsx
=> [FIX] bn support >=18 unitDecimals. Handle can't exchange error

src/navigation/wallet/screens/send/confirm/Shared.tsx
Fixes https://github.com/bitpay/bitpay-app/pull/605
=> Fix: show fiat value for livenet tx on Confirm screen

src/navigation/wallet/screens/KeyOverview.tsx, src/navigation/wallet/screens/KeySettings.tsx, src/navigation/wallet/screens/UpdateKeyOrWalletName.tsx
* Also update the key/wallet name on Settings
=> Fix: do not allow save empty key/wallet name

src/navigation/wallet/screens/send/confirm/PayProConfirm.tsx, src/navigation/zenledger/screens/ZenLedgerImport.tsx, src/store/app/app.effects.ts, src/store/shop/shop.models.ts
* Merchant Payment
* ZenLedger Import
* Funded Wallet
=> Feat[RN-856]: new events for Segment

src/navigation/services/buy-crypto/components/PaymentMethodModal.tsx, src/navigation/services/buy-crypto/screens/BuyCryptoRoot.tsx, src/navigation/services/buy-crypto/utils/buy-crypto-utils.ts, src/navigation/services/swap-crypto/screens/SwapCryptoRoot.tsx, src/navigation/wallet/screens/WalletDetails.tsx, src/store/app/app.effects.ts, src/store/buy-crypto/buy-crypto.effects.ts, src/store/external-services/external-services.effects.ts, src/store/external-services/external-services.types.ts, src/store/location/location.actions.ts, src/store/location/location.effects.ts, src/store/location/location.models.ts, src/store/location/location.reducer.ts, src/store/location/location.types.ts, src/store/shop/shop.effects.ts
This PR needs: https://github.com/bitpay/bitcore/pull/3547
=> Ref: location and getExternalServicesConfig

src/constants/WalletConnectV2.tsx, src/constants/config.ts, src/navigation/wallet-connect/screens/WalletConnectRequestDetails.tsx, src/store/scan/scan.effects.ts
=> [RN-621]: kovan to goerli migration

src/navigation/services/components/ToWalletSelectorModal.tsx, src/navigation/services/swap-crypto/screens/SwapCryptoRoot.tsx, src/navigation/services/swap-crypto/utils/changelly-utils.ts, src/store/swap-crypto/effects/changelly/changelly.ts
This PR needs: https://github.com/bitpay/bitcore/pull/3554
=> Ref: Changelly V2

src/components/button/Button.tsx, src/components/list/CurrencySelectionRow.tsx, src/components/modal/pin/PinModal.tsx, src/components/virtual-keyboard/VirtualKeyboard.tsx, src/navigation/auth/screens/CreateAccount.tsx, src/navigation/auth/screens/ForgotPassword.tsx, src/navigation/auth/screens/Login.tsx, src/navigation/auth/screens/VerifyEmail.tsx, src/navigation/onboarding/components/OnboardingFinishModal.tsx, src/navigation/onboarding/screens/CreateKey.tsx, src/navigation/onboarding/screens/Notifications.tsx, src/navigation/onboarding/screens/OnboardingStart.tsx, src/navigation/onboarding/screens/Pin.tsx, src/navigation/onboarding/screens/TermsOfUse.tsx, src/navigation/wallet/components/FileOrText.tsx, src/navigation/wallet/components/RecoveryPhrase.tsx, src/navigation/wallet/screens/Backup.tsx, src/navigation/wallet/screens/CurrencySelection.tsx, src/navigation/wallet/screens/Import.tsx, src/navigation/wallet/screens/RecoveryPhrase.tsx, src/navigation/wallet/screens/VerifyPhrase.tsx
https://docs.google.com/document/d/1nxKJD4C_OfUwZgnzqnDPErW5WATqkMIdHDDXg04JQnQ/edit
=> [RN-865]: Ids for Testlio

package.json, yarn.lock
This PR bumps the BWC version to 10.0.2.
=> BWC bump to 10.0.2

src/store/wallet/effects/status/status.ts
To reproduce: 
1. Create a transaction proposal
2. Close the app and remove the transaction with the other copayer
3. Open the app and go to wallet details with the first copayer
=> [FIX] check for stored multisig proposals

src/navigation/onboarding/screens/OnboardingStart.tsx
=> Fix: updated text from Onboarding Screen

src/constants/TransactionIcons.tsx, src/navigation/wallet/screens/TransactionProposalNotifications.tsx, src/navigation/wallet/screens/WalletDetails.tsx, src/store/wallet/effects/transactions/transactions.ts
Need help for testing amazon giftcard
=> [REF] store index instead of React Element for uiIcons

src/navigation/services/buy-crypto/screens/BuyCryptoOffers.tsx
This PR also removes rate from offers cards
=> Feat: Best offer tag

src/store/wallet/wallet.reducer.ts
```
{
urgent: isEvmOrToken ? t('High') : t('Urgent'),
priority: isEvmOrToken ? t('Average') : t('Priority'),
normal: isEvmOrToken ? t('Low') : t('Normal'),
economy: t('Economy'),
superEconomy: t('Super Economy'),
custom: t('Custom'),
};
```
=> [REF] Default network policy for evm to average

src/navigation/wallet/screens/Copayers.tsx
=> Fix: cannot find name "Status"

src/navigation/services/swap-crypto/screens/ChangellyCheckout.tsx, src/store/swap-crypto/effects/changelly/changelly.ts
This PR needs: https://github.com/bitpay/bitcore/pull/3573
=> Ref: Changelly get exchange fees

src/navigation/wallet/screens/WalletDetails.tsx, src/store/wallet/effects/send/send.ts
issues in the message and in the confirm UI: 
Fixed:
=> [FIX] CPFP speedup btc

src/components/banner/Banner.tsx, src/components/list/TransactionProposalRow.tsx, src/components/modal/ongoing-process/OngoingProcess.tsx, src/navigation/wallet/screens/TransactionProposalDetails.tsx, src/navigation/wallet/screens/TransactionProposalNotifications.tsx, src/navigation/wallet/screens/WalletDetails.tsx, src/store/app/app.effects.ts, src/store/wallet/wallet.models.ts
txs renamed to txp
re-broadcast TXP feature added
Check PayPro details added
Missing status messages added
Show "Spendable balance modal" when click on "Total Locked Balance" row
Fixed "danger" links buttons to show the color correctly
=> Ref: TXP Details

src/navigation/bitpay-id/components/TwoFactorRequiredModal.tsx
=> Fix: UI truncated button

patches/react-native-mail+6.1.1.patch
https://github.com/chirag04/react-native-mail/issues/196
=> Fix: error sending email on Android >= 13

src/navigation/card/components/CardDashboard.tsx, src/navigation/wallet/screens/send/confirm/DebitCardConfirm.tsx, src/store/wallet/utils/wallet.ts
* Check is there is any Coinbase Account with funds before goes to Buy Screen.
* List Coinbase Accounts without verify for Threshold (until it creates the invoice).
=> RN-943: TopUp (Add Funds): should check if there are Coinbase Accounts

src/navigation/bitpay-id/screens/ReceiveSettings.tsx, src/navigation/wallet/screens/send/confirm/PayProConfirm.tsx, src/navigation/wallet/screens/send/confirm/Shared.tsx
* Also show Coinbase Accounts for paypro payments
=> Fix [RN-963]: Show compatible wallets on "Receive via Email"

src/navigation/services/buy-crypto/screens/BuyCryptoOffers.tsx, src/store/buy-crypto/buy-crypto.models.ts, src/store/scan/scan.effects.ts
This PR also fixes the handling of the incoming data from redirect url
=> Fix: sardine default payment method

src/Root.tsx, src/components/modal/in-app-notification/InAppNotification.tsx, src/navigation/wallet-connect/components/Connections.tsx, src/store/app/app.actions.ts, src/store/app/app.effects.ts, src/store/app/app.models.ts, src/store/app/app.reducer.ts, src/store/app/app.types.ts, src/store/wallet-connect-v2/wallet-connect-v2.effects.ts, src/store/wallet/utils/wallet.ts
(WalletConnect implementation only)
=> [RN-977]: In-app notifications

src/api/user/user.queries.ts, src/navigation/bitpay-id/screens/ProfileSettings.tsx, src/store/bitpay-id/bitpay-id.models.ts
Show "Receive Email address" and "Two-Factor Authentication" options only if email has been verified.
=> Feat: check if email verified on Profile screen

src/components/modal/in-app-notification/InAppNotification.tsx, src/navigation/wallet-connect/screens/WalletConnectHome.tsx, src/store/app/app.effects.ts
- adjusted timing
- adjusted backdrop
- removed reset
- added context to auto open confirm if from notification
- reversed requests list
=> Walletconnect v2 notification adjustments

src/lib/apple-push-provisioning/ApplePushProvisioning.ts, src/lib/google-push-provisioning/GooglePushProvisioning.ts
This PR fixes the error where null is passed to the NativeEventEmitter ctor.
=> Ensure non-null value passed to NativeEventEmitter

index.js, ios/Podfile.lock, package.json, src/AppInitialization.tsx, src/navigation/tabs/settings/general/screens/Theme.tsx, src/navigation/wallet/components/RecoveryPhrase.tsx, src/store/app/app.actions.ts, src/store/app/app.effects.ts, src/store/app/app.reducer.ts, src/store/app/app.types.ts, src/store/index.ts, src/store/wallet/effects/import/import.ts
something to keep in mind when reviewing the code: Is not possible to add logs when opening the app for the first time as everything is deleted with the new storage. Also, I avoid adding logs after migration also, as this could corrupt the recently stored data.
=> [FEAT] mmkv storage migration

src/components/modal/pin/PinModal.tsx
The "confirm pin" when setting a pin view was skipped. This PR will fix that and also I refactor some part of the code to avoid unnecessary re renders.
=> [FIX] confirm PIN section

src/navigation/tabs/shop/components/GiftCardCreditsItem.tsx, src/navigation/tabs/shop/components/MyGiftCards.tsx, src/navigation/tabs/shop/gift-card/screens/BuyGiftCard.tsx, src/navigation/tabs/shop/gift-card/screens/GiftCardDetails.tsx
Ensures the `My Gift Cards` section in the `Shop` tab renders properly with the new `react-native-reanimated-carousel` package.
=> Fix `My Gift Cards` section

src/navigation/wallet/screens/send/SendTo.tsx
* Hide "Paste from clipboard" when using SearchInput
* Improves view if `searchIsEmailAddress`
* Adds margin top for "Contacts" title
=> Fix: sendTo UI details

src/store/wallet/effects/rates/rates.ts
[2023-09-22T22:30:34.661Z] [debug] getTokenRates: get request to: https://bws.bitpay.com/bws/api/v1/service/coinGecko/getRates///eth
[2023-09-22T22:30:34.887Z] [error] getTokenRates: failed (continue anyway) Request failed with status code 404
=> [FIX] skip if no contract address

src/navigation/wallet/screens/send/confirm/Confirm.tsx, src/navigation/wallet/screens/send/confirm/Shared.tsx, src/store/wallet/effects/send/send.ts
=> [FIX] confirm total amount ui issue

src/store/app/app.types.ts
Duplicated here: https://github.com/bitpay/bitpay-app/blob/master/src/store/app/app.types.ts#L144
=> Fix: remove duplicated ShowBottomNotificationModal interface

src/navigation/card/components/CardIntro.tsx
=> Fix: card intro title small devices adjustment

src/components/modal/bottom-notification/BottomNotification.tsx, src/navigation/tabs/shop/bill/components/BillAccountPill.tsx, src/navigation/tabs/shop/bill/components/BillItem.tsx, src/navigation/tabs/shop/bill/components/BillStatus.tsx, src/navigation/tabs/shop/bill/components/PaymentList.tsx, src/navigation/tabs/shop/bill/screens/PayAllBills.tsx, src/navigation/tabs/shop/bill/screens/PayBill.tsx, src/navigation/tabs/shop/bill/screens/Payment.tsx, src/navigation/tabs/shop/bill/screens/Payments.tsx, src/navigation/tabs/shop/bill/utils.ts, src/navigation/tabs/shop/components/Bills.tsx, src/navigation/tabs/shop/components/UserInfo.tsx, src/navigation/tabs/shop/components/styled/ShopTabComponents.tsx, src/navigation/tabs/shop/gift-card/screens/GiftCardDetails.tsx, src/navigation/wallet/screens/send/confirm/BillConfirm.tsx, src/navigation/wallet/screens/send/confirm/GiftCardConfirm.tsx, src/store/shop/shop.effects.ts, src/store/shop/shop.models.ts
Adds the ability to pay multiple bills in a single transaction. Also displays payments from removed bills in payment history and includes miscellaneous gift card fixes.
=> Pay All Bills and other Bill Pay and Gift Card Improvements

LICENSE
=> Specify license

locales/en/translation.json, locales/es/translation.json, package.json, src/components/icons/external-services/banxa/banxa-logo.tsx, src/navigation/services/buy-crypto/components/PaymentMethodModal.tsx, src/navigation/services/buy-crypto/components/terms/banxaTerms.tsx, src/navigation/services/buy-crypto/constants/BuyCryptoConstants.tsx, src/navigation/services/buy-crypto/screens/BuyCryptoOffers.tsx, src/navigation/services/buy-crypto/screens/BuyCryptoRoot.tsx, src/navigation/services/buy-crypto/utils/banxa-utils.ts, src/navigation/services/buy-crypto/utils/buy-crypto-utils.ts, src/navigation/tabs/settings/components/ExternalServices.tsx, src/navigation/tabs/settings/external-services/ExternalServicesStack.tsx, src/navigation/tabs/settings/external-services/screens/BanxaDetails.tsx, src/navigation/tabs/settings/external-services/screens/BanxaSettings.tsx, src/store/buy-crypto/buy-crypto.actions.ts, src/store/buy-crypto/buy-crypto.effects.ts, src/store/buy-crypto/buy-crypto.models.ts, src/store/buy-crypto/buy-crypto.reducer.ts, src/store/buy-crypto/buy-crypto.types.ts, src/store/buy-crypto/effects/banxa/banxa.ts, src/store/external-services/external-services.types.ts, src/store/scan/scan.effects.ts, src/store/wallet/utils/validations.ts, yarn.lock
This PR needs: https://github.com/bitpay/bitcore/pull/3619
=> Feat: Banxa integration

src/constants/WalletConnectV2.tsx, src/navigation/wallet-connect/components/WCV2WalletSelector.tsx, src/navigation/wallet-connect/screens/WalletConnectConfirm.tsx, src/navigation/wallet-connect/screens/WalletConnectHome.tsx, src/navigation/wallet-connect/screens/WalletConnectRequestDetails.tsx, src/navigation/wallet-connect/screens/WalletConnectStart.tsx, src/store/wallet-connect-v2/wallet-connect-v2.actions.ts, src/store/wallet-connect-v2/wallet-connect-v2.effects.ts
1. check for optional namespaces and add all possible wallets from the same key to the session
2. adding wallet_addEthereumChain to the supported methods
3. fix for deposit and withdraw from matic
=> [FIX] check optional namespaces for getting wallets

package.json
https://github.com/bitpay/bitcore/pull/3659
=> [FIX] issue with the getStatusAll method on iOS 17 devices

src/navigation/wallet/screens/WalletDetails.tsx
Known issue: https://github.com/facebook/react-native/issues/38090
=> Fix: removed momentum scroll that doesn't work on DesktopApp

scripts/allowed-url-prefixes.js
Increase allowed URL prefix specificity, add MethodFi CDN URL to allowed URL prefix list in production, and add localhost in dev mode to ensure local assets display properly during development.
=> Improve Allowed URL Prefixes

src/navigation/wallet/screens/wallet-settings/ExportWallet.tsx
Fixes https://github.com/bitpay/bitpay-app/pull/971
=> Fix: Export Wallet

src/Root.tsx
This PR will need a refactor when https://github.com/bitpay/bitpay-app/pull/1005 is merged
EDIT: Refactor done!
=> Ref: Blur specific screens

src/navigation/tabs/home/HomeRoot.tsx, src/navigation/tabs/home/components/Crypto.tsx, src/navigation/tabs/home/components/quick-links/QuickLinksCarousel.tsx
Fix item height on Android devices
=> Fix: my crypto slider

declarations.d.ts, scripts/allowed-url-prefixes.js, src/api/zenledger/index.ts, src/api/zenledger/zenledger.constants.ts, src/api/zenledger/zenledger.types.ts, src/navigation/zenledger/screens/ZenLedgerImport.tsx, src/navigation/zenledger/screens/ZenLedgerIntro.tsx, src/store/app/app.effects.ts, src/store/index.ts, src/store/zenledger/index.ts, src/store/zenledger/zenledger.actions.ts, src/store/zenledger/zenledger.effects.ts, src/store/zenledger/zenledger.models.ts, src/store/zenledger/zenledger.reducer.ts, src/store/zenledger/zenledger.types.ts
* Create Token if it doesn't exist and Check if it expired only when using "CreatePortfolio".
* Create Portfolio: send wallet addresses, name, etc and return aggcode and url.
=> Ref: New Zenledger API

src/navigation/auth/screens/Login.tsx, src/navigation/auth/screens/TwoFactor.Pair.tsx
Current error: after login successfully, and click on "Back", I see the login form again. I've to click on Back button again to return Home Screen.
=> Fix: After login BitPay ID, go back button returns Home Screen

src/navigation/tabs/shop/ShopHome.tsx, src/navigation/tabs/shop/components/GiftCardCatalog.tsx, src/navigation/tabs/shop/components/ShopCarouselList.tsx, src/navigation/tabs/shop/components/ShopOnline.tsx
1. Fix shop online carousel item styles
2. Improve shop carousel scroll performance (especially on older android devices)
=> Shop Online Fixes

src/store/bitpay-id/bitpay-id.effects.ts
If no renew EID after logout from BitPay, I'm going to continue seeing In-App messages, Cards, etc, specifically for a BitPay User.
=> Fix: Renew Braze EID after logout from BitPayID

src/Root.tsx, src/navigation/tabs/TabsStack.tsx, src/navigation/tabs/settings/components/Connections.tsx, src/navigation/tabs/shop/bill/components/BillItem.tsx, src/navigation/tabs/shop/bill/components/BillList.tsx, src/navigation/tabs/shop/bill/screens/BillSettings.tsx, src/navigation/tabs/shop/bill/screens/ConnectBills.tsx, src/navigation/tabs/shop/bill/screens/ConnectBillsOptions.tsx, src/navigation/tabs/shop/bill/screens/PayAllBills.tsx, src/navigation/tabs/shop/bill/screens/PayBill.tsx, src/navigation/tabs/shop/bill/screens/Payment.tsx, src/navigation/tabs/shop/bill/utils.ts, src/navigation/tabs/shop/components/Bills.tsx, src/navigation/wallet/screens/send/confirm/BillConfirm.tsx, src/store/bitpay-id/bitpay-id.effects.ts
1. Ensures pull-to-refresh is not required after a user connects their first bill
2. Improves bill pay events
=> Bill Pay Fixes

src/navigation/services/buy-crypto/screens/BuyCryptoOffers.tsx, src/navigation/services/buy-crypto/screens/BuyCryptoRoot.tsx, src/navigation/services/buy-crypto/utils/banxa-utils.ts
With these changes, the Banxa offer should display faster on the offers page.
It also includes a refactor necessary for an upcoming Banxa update regarding payment methods.
=> Ref: Banxa payment methods

src/navigation/wallet/screens/WalletDetails.tsx, src/store/wallet/effects/transactions/transactions.ts
=> Fix: Remove fiat value for Stable Coins

src/components/list/KeyWalletsRow.tsx, src/navigation/services/components/ToWalletSelectorModal.tsx, src/navigation/wallet/screens/GlobalSelect.tsx, src/navigation/wallet/screens/send/SendTo.tsx, src/store/wallet/utils/wallet.ts
=> Fix: disable no backup wallets

src/navigation/tabs/settings/components/Notifications.tsx, src/navigation/tabs/settings/notifications/screens/PushNotifications.tsx
https://github.com/bitpay/bitpay-app/assets/237435/92f87521-0bed-4ad9-85b2-2b22481c238a
=> Fix: setting push notifications twice

src/navigation/wallet/screens/Copayers.tsx, src/navigation/wallet/screens/JoinMultisig.tsx
Also UI adjustment for Copayer Screen
=> Fix: Joining a multisig wallet

src/navigation/services/buy-crypto/screens/BuyCryptoOffers.tsx
**AS PART OF THIS PR**
> Added testId for crypto offers with `offer.key `as the value
=> feat: Add testId for crypto offers

src/store/wallet/effects/send/send.ts
* Avoid that a global constant override into an Async function.
=> Fix: Send multiple recipients

src/store/analytics/analytics.effects.ts, src/store/app/app.effects.ts
Reverts bitpay/bitpay-app#1169
=> Revert "Fix: adds new event for app installed"

src/navigation/wallet/screens/KeySettings.tsx
=> Fix: position for search-component on KeySettings

src/navigation/tabs/TabContainer.tsx, src/navigation/tabs/TabsStack.tsx, src/navigation/tabs/home/HomeRoot.tsx, src/navigation/tabs/home/components/Styled.tsx, src/navigation/tabs/shop/ShopHome.tsx, src/navigation/tabs/shop/ShopStack.tsx, src/navigation/tabs/shop/bill/BillStack.tsx, src/navigation/tabs/shop/bill/screens/BillsHome.tsx
Also simplifies and standardizes top-level tab headers.
=> Fix tab jumping on initial load on iOS

src/components/list/WalletRow.tsx
=> Ref: show account number and contract address

src/constants/currencies.ts, src/store/wallet/effects/create/create.ts
Revert: https://github.com/bitpay/bitpay-app/pull/1224
=> Revert: Fix wallet name when creating new key for new chains

src/navigation/wallet/screens/send/confirm/Shared.tsx, src/store/wallet/effects/send/send.ts, src/store/wallet/wallet.models.ts
=> Fix: show badge on Confirm View for SendTo field

src/constants/NavigationOptions.tsx
Switching to default animation as it feels snappier and more performant
=> Default Android navigation animation

src/api/coinbase/coinbase.constants.ts, src/api/coinbase/coinbase.types.ts, src/api/coinbase/index.ts, src/components/list/KeyWalletsRow.tsx, src/navigation/coinbase/components/CoinbaseDashboard.tsx, src/navigation/coinbase/components/CoinbaseIcon.tsx, src/navigation/coinbase/components/CoinbaseSettingsOption.tsx, src/navigation/coinbase/screens/CoinbaseAccount.tsx, src/navigation/coinbase/screens/CoinbaseSettings.tsx, src/navigation/coinbase/screens/CoinbaseTransaction.tsx, src/navigation/wallet/screens/send/confirm/Confirm.tsx, src/store/coinbase/coinbase.effects.ts, src/store/wallet/utils/wallet.ts
* Upgrade to Oauth2: https://docs.cdp.coinbase.com/sign-in-with-coinbase/docs/changelog/#2024-mar-27
* Removes deprecated params for transaction object into Account and Transaction screens
* Added new_version_opt_in to receive new fields
* Fixed Setting icon
* Added re-connect function for Unauthorized response
* Fixed sign out
* Fixed back to Coinbase after transaction sent
* Removed “incomplete” badge for all Coinbase Accounts
* Fixed Withdrawal
* Fixed Description and Icons for transaction details (Deposit and Withdrawal)
* Handle invalid token (Unauthorized)
=> Fix: updates coinbase integration and fix connection issues

src/navigation/services/swap-crypto/screens/ThorswapCheckout.tsx, src/navigation/wallet/screens/GlobalSelect.tsx, src/store/wallet/utils/currency.ts
It was tested for an ETH -> USDC (ETH) swap through the Uniswap V2 provider: https://etherscan.io/tx/0xb858efa5b091cf7cb0fb6688458ccd3d7f344ae6f7f5fb33526ce0956c6c6bcf
Variants would need to be tested, such as using different providers, or different pairs.
=> Fix: Thorswap swap when ETH wallet is the source of funds

src/navigation/tabs/home/HomeRoot.tsx, src/navigation/wallet/screens/TransactionDetails.tsx, src/navigation/wallet/screens/TransactionProposalDetails.tsx, src/navigation/wallet/screens/TransactionProposalNotifications.tsx, src/store/wallet/effects/transactions/transactions.ts
=> Fix: list correctly txp for EVM

src/navigation/wallet/screens/PriceCharts.tsx
1. Displays min and max prices in price chart
2. Shows the timestamp of selected price points
3. Hides stale price data via a skeleton loader when new price data is loading
=> [REF] Price Chart Improvements

src/navigation/coinbase/screens/CoinbaseAccount.tsx, src/navigation/wallet/screens/GlobalSelect.tsx
* Changed old modal for new GlobalSelector modal
* Ref: GlobalSelector to filter wallets for modals
=> Fix: Coinbase and GlobalSelector

src/components/blockie/Blockie.tsx, src/components/blockie/hsl2rgb.js, src/components/blockie/pnglib.js, src/components/chain-search/ChainSearch.tsx, src/components/list/AccountListRow.tsx, src/components/list/KeyWalletsRow.tsx, src/navigation/bitpay-id/screens/ReceiveSettings.tsx, src/navigation/services/swap-crypto/screens/SwapCryptoRoot.tsx, src/navigation/wallet/screens/AccountDetails.tsx, src/navigation/wallet/screens/GlobalSelect.tsx, src/navigation/wallet/screens/PriceCharts.tsx
this fixes: when navigating into a key view a consistent flash happens now on IOS (havent tested android yet).
Also generally improves performance when evm icons are involved.
=> [REF] blockie component - search component and receive settings fixes 

src/components/chain-search/ChainSearch.tsx, src/components/modal/chain-selector/ChainSelector.tsx
This update changes the filter to show only the options that match the items in the list. For example, if the list has BTC and LTC wallets, the filter will only show BTC and LTC as options.
=> [REF] Filter options based on available chains

src/navigation/wallet/screens/GlobalSelect.tsx
The Global selector is not taking into account the list of customCurrencies to create the list of swapFrom, sell and possibly coinbase.
=> Fix: Global Selector custom Currencies (swap, sell)

src/components/button/Button.tsx, src/navigation/coinbase/screens/CoinbaseSettings.tsx
=> Fix: button style for type danger/outline

package.json, src/Root.tsx, src/components/amount/AmountModal.tsx, src/components/modal/base/sheet/SheetModal.tsx, src/components/modal/bottom-notification/BottomNotification.tsx, src/components/modal/transact-menu/TransactMenu.tsx, src/navigation/tabs/settings/about/screens/SessionLog.tsx, src/navigation/tabs/settings/components/Security.tsx, src/navigation/tabs/shop/components/FilterSheet.tsx, src/navigation/tabs/shop/gift-card/screens/GiftCardDetails.tsx, src/navigation/wallet/components/DeleteConfirmationModal.tsx, src/navigation/wallet/components/OptionsSheet.tsx, src/navigation/wallet/components/ReceiveAddress.tsx, yarn.lock
Uses https://github.com/gorhom/react-native-bottom-sheet to improve the performance of commonly used sheet modals.
=> [REF] Improve Sheet Modal Performance

src/utils/helper-methods.ts
This ensures that if one wallet fails (e.g. it's not connected to BWS), it doesn't block the process for the remaining wallets.
=> [REF] add try catch to wallet address fix

src/store/wallet/effects/create/create.ts
In this PR I avoid the auto-creation of "Custom tokens" if they are not included in our list of tokens to add in the basic creation flow.
The user can still manually add custom tokens from the normal flow in Account details.
=> Ref: prevent auto-detect tokens from adding potential spam

src/components/list/KeyWalletsRow.tsx, src/components/list/WalletRow.tsx, src/navigation/wallet/screens/send/confirm/BillConfirm.tsx, src/navigation/wallet/screens/send/confirm/GiftCardConfirm.tsx, src/navigation/wallet/screens/send/confirm/PayProConfirm.tsx, src/navigation/wallet/screens/send/confirm/Shared.tsx, src/store/wallet/utils/wallet.ts
Paying gift card, bill pay, and general invoices via Coinbase is currently not working after the account refactor. This PR gets Coinbase payments working again.
=> [FIX] Coinbase payments

src/navigation/tabs/contacts/components/ContactIcon.tsx, src/navigation/wallet/components/MultipleOutputsTx.tsx
=> Fix: contacts icon for multiple recipients list

src/navigation/tabs/contacts/components/ContactIcon.tsx
Also fix: https://github.com/bitpay/bitpay-app/pull/1370
=> Fix: contacts icons on Confirm screen

src/navigation/bitpay-id/utils/bitpay-id-utils.ts, src/store/wallet/effects/paypro/paypro.ts
Requires: https://github.com/bitpay/bitcore/pull/3808
=> Fix: invoice payment with POL/MATIC

src/navigation/tabs/shop/gift-card/screens/BuyGiftCard.tsx, src/navigation/tabs/shop/gift-card/screens/GiftCardDetails.tsx, src/navigation/wallet/screens/send/confirm/GiftCardConfirm.tsx
1. Ensures redemption functionality is restored when a gift card is unarchived
2. Saves boosted amount in transaction memo after a boosted gift card purchase
3. Includes new `visibleCoupon` field in gift card events
=> [FIX] Misc Gift Card Fixes

src/store/app/app.effects.ts
=> Fix: filter only supported type of IAM by the app and avoid freeze

src/navigation/services/buy-crypto/screens/BuyCryptoRoot.tsx, src/navigation/wallet/screens/GlobalSelect.tsx
=> [FIX] pol name in buy crypto

android/app/src/main/AndroidManifest.xml, ios/Podfile, ios/Podfile.lock, package.json, src/navigation/onboarding/screens/Notifications.tsx, src/navigation/tabs/settings/components/Notifications.tsx, src/navigation/tabs/settings/notifications/screens/PushNotifications.tsx, src/store/app/app.effects.ts, yarn.lock
Fix:
* Ask for Notification permissions on Android 13+
* Open Settings when Notification is not allowed
* Ref: Android/iOS checking status
=> Chore: Upgrade react-native-permissions

src/constants/BiometricError.ts, src/navigation/onboarding/screens/Pin.tsx, src/navigation/tabs/settings/components/Security.tsx, src/store/app/app.effects.ts
* Ask open App Settings to enable FaceID manually
=> Fix: check iOS permissions for FaceID

src/components/modal/base/sheet/SheetModal.tsx
Workaround to add TestID since plugin doesn't support it.
https://github.com/gorhom/react-native-bottom-sheet/issues/1429
=> Fix: add testID on SheeModals

src/api/coinbase/index.ts
=> Fix: connect to Coinbase (redirect) on Android

src/components/amount/AmountModal.tsx, src/components/modal/bottom-notification/BottomNotification.tsx, src/components/modal/transact-menu/TransactMenu.tsx, src/navigation/coinbase/screens/CoinbaseAccount.tsx, src/navigation/services/buy-crypto/screens/BuyCryptoOffers.tsx, src/navigation/services/buy-crypto/screens/BuyCryptoRoot.tsx, src/navigation/services/swap-crypto/components/FromWalletSelectorModal.tsx, src/navigation/services/swap-crypto/screens/SwapCryptoRoot.tsx, src/navigation/tabs/settings/about/screens/SessionLog.tsx, src/navigation/tabs/settings/components/Security.tsx, src/navigation/tabs/shop/components/FilterSheet.tsx, src/navigation/wallet/components/DeleteConfirmationModal.tsx, src/navigation/wallet/components/OptionsSheet.tsx, src/navigation/wallet/components/ReceiveAddress.tsx, src/navigation/wallet/screens/GlobalSelect.tsx, src/navigation/wallet/screens/PaperWallet.tsx
* Also add TestID for provider name (Crypto Offers View)
=> Fix: TestID using old bottom sheet

src/api/coinbase/coinbase.types.ts, src/api/coinbase/index.ts, src/store/coinbase/coinbase.actions.ts, src/store/coinbase/coinbase.effects.ts, src/store/coinbase/coinbase.reducer.ts, src/store/coinbase/coinbase.types.ts, src/store/coinbase/index.ts
Also set endpoint to "Get Supported Crypto Currencies" from Coinbase
=> Ref: check if Coinbase Supports BitPay selected currency

src/navigation/coinbase/screens/CoinbaseAccount.tsx
=> Fix: no show skeleton when click on Deposit/Withdraw button

src/navigation/wallet/screens/BackupOnboarding.tsx
Adds a second security layer before show the backup words.
=> Fix: if Biometric is enabled, check it before show Backup words

patches/@react-navigation+elements+1.3.21.patch, src/components/settings/Settings.tsx, src/navigation/tabs/settings/components/General.tsx, src/navigation/wallet/screens/KeyOverview.tsx
Temporary workaround for https://github.com/software-mansion/react-native-screens/issues/2219
=> Fix: android header pressability

src/navigation/services/buy-crypto/utils/ramp-utils.ts
=> Feat: Ramp update of buy tokens

src/components/modal/base/sheet/SheetModal.tsx
Reverts bitpay/bitpay-app#1540
=> Revert "[FIX] bottom-sheet animation issues"

src/components/form/BoxInput.tsx, src/navigation/tabs/settings/about/screens/SessionLog.tsx, src/navigation/tabs/settings/notifications/screens/PushNotifications.tsx
=> Bug/android UI issues 02

src/navigation/tabs/settings/general/screens/customize-home/CustomizeHome.tsx
Known issue using Fabric. https://github.com/software-mansion/react-native-screens/issues/2339 
* Replaced `Flatlist` by `Flashlist`
=> Fix: Android issue, save layout on CustomizeHome screen

src/Root.tsx, src/components/modal/base/sheet/SheetModal.tsx, src/components/modal/ongoing-process/OngoingProcess.tsx
Moves `BottomSheetModalProvider` back to `Root.tsx`, since not having it there breaks how some bottom sheets are displayed (such as the send options bottom sheet)
=> Fix: broken send options bottom sheet

src/navigation/tabs/shop/components/Bills.tsx, src/navigation/tabs/shop/gift-card/screens/BuyGiftCard.tsx
This PR adjusts minHeight values on iOS to better fit page content in BuyGiftCard.tsx and Bills.tsx.
=> Fix: BuyGiftCard.tsx and Bills.tsx minHeight on iOS

src/navigation/bitpay-id/utils/bitpay-id-utils.ts
needs bwc bump: https://github.com/bitpay/bitcore/pull/3866
=> [FIX] get correct currency code for usdt

src/Root.tsx, src/components/modal/ongoing-process/OngoingProcess.tsx, src/navigation/wallet/components/FileOrText.tsx, src/navigation/wallet/components/RecoveryPhrase.tsx, src/store/app/app.effects.ts, src/store/index.ts, src/store/transforms/encrypt.ts, src/store/transforms/transforms.ts, src/store/wallet/effects/address/address.ts, src/utils/helper-methods.ts
Skip unnecessary dispatch when fixing addresses. Especially in the import process to avoid the Maximum Update Depth Exceeded error that is blocking imports
=> [FIX] import fix wallet addresses process

src/components/amount/Amount.tsx, src/components/amount/AmountModal.tsx, src/components/archax/archax-banner.tsx, src/components/archax/archax-footer.tsx, src/components/icons/currency-symbol/CurrencySymbol.tsx, src/components/styled/Containers.tsx, src/components/styled/Text.tsx, src/components/swap-button/SwapButton.tsx, src/components/virtual-keyboard/VirtualKeyboard.tsx, src/components/virtual-keyboard/VirtualKeyboardButtonAnimation.tsx, src/store/index.ts, src/store/transforms/encrypt.ts, src/store/transforms/transforms.ts
This PR should fix cases where the "Continue" button appears below the UI, making it inaccessible for Android users.
It also addresses various cases where Archax banners are displayed, especially on smaller devices, preventing elements from collapsing.
=> Fix: Amount and AmountModal UI

src/components/chain-search/ChainSearch.tsx, src/components/styled/Containers.tsx, src/navigation/wallet/screens/AccountDetails.tsx, src/navigation/wallet/screens/KeyOverview.tsx
=> Fix: chain filter collision with input

src/navigation/wallet/components/PaymentSent.tsx
Removes the background color interpolation from white to green so that the background color is always a static green and makes the checkmark and footer button animations complete faster and more subtly.
=> Ref: make payment sent modal animations more subtle

android/app/src/main/java/com/bitpay/wallet/CustomInAppMessageManagerListener.java, android/app/src/main/java/com/bitpay/wallet/MainActivity.kt, android/app/src/main/java/com/bitpay/wallet/MainApplication.kt, src/Root.tsx
* Cache IAM instead "DISCARD"
* Commented out non-required functions
=> Fix: receive IAM on Android

src/Root.tsx
https://bitpayprod.atlassian.net/jira/software/projects/RN/boards/42?selectedIssue=RN-1858
=> [FIX] add extra logs for svm migration

src/components/list/KeyWalletsRow.tsx, src/components/list/WalletRow.tsx, src/components/styled/Containers.tsx, src/navigation/wallet/screens/send/confirm/PayProConfirm.tsx, src/navigation/wallet/screens/send/confirm/Shared.tsx, src/store/shop/shop.models.ts, src/store/wallet/effects/paypro/paypro.ts, src/store/wallet/utils/wallet.ts
* Fixed click on wallet selector
* Show all supported currencies by BitPay
* Label "Temporarily disabled"
* Label "Not supported"
=> Feat: list all supported currencies and show if it is temporarily disabled

src/navigation/services/sell-crypto/screens/MoonpaySellCheckout.tsx, src/navigation/services/sell-crypto/screens/RampSellCheckout.tsx, src/navigation/services/sell-crypto/screens/SimplexSellCheckout.tsx, src/navigation/services/sell-crypto/utils/moonpay-sell-utils.ts, src/navigation/services/swap-crypto/screens/ChangellyCheckout.tsx
This also includes a fix to show Solana tokens in Moonpay-sell
=> Fix: use ata toAddress in swap and sell for solana tokens

src/navigation/services/sell-crypto/screens/MoonpaySellCheckout.tsx, src/navigation/services/sell-crypto/screens/RampSellCheckout.tsx, src/navigation/services/sell-crypto/screens/SimplexSellCheckout.tsx, src/navigation/services/swap-crypto/screens/ChangellyCheckout.tsx
This PR needs: https://github.com/bitpay/bitpay-app/pull/1885
=> Fix: create destination ataAddress if necessary in swap/sell
