bitpay/bitpay-app

src/navigation/tabs/shop/components/styled/ShopTabComponents.tsx
src/navigation/tabs/shop/gift-card/GiftCardStack.tsx
src/navigation/tabs/shop/gift-card/screens/BuyGiftCard.tsx
src/navigation/wallet/screens/send/confirm/DebitCardConfirm.tsx
src/navigation/wallet/screens/send/confirm/GiftCardConfirm.tsx
src/navigation/wallet/screens/send/confirm/PayProConfirm.tsx
src/navigation/wallet/screens/send/confirm/Shared.tsx
src/store/wallet/utils/wallet.ts

Currently wallet selector logic is duplicated across 3 confirm pages. This PR consolidates wallet selector logic by turning it into a shared component, making future wallet selector changes more maintainable. 
This PR also:
1. Fixes an issue with the wallet selector not appearing on the paypro confirm screen after a successful paypro scan
2. Fixes a positioning issue with the settings navbar button on the gift card details screen
3. Includes misc improvements to the mastercard gift card purchase flow
4. Automatically selects the only wallet available on the gift card, debit card, and general paypro confirm screens (if only one wallet is available) while making auto-selection 500ms faster by eliminating an unneeded delay

Refactor wallet selector to be DRYer and misc fixes

---

src/navigation/tabs/settings/general/screens/AltCurrencySettings.tsx

When selecting an altCurrency and exiting the keyboard reopens and flashes - this PR dismisses it before navigating. I also refactored and removed the on going process.

[FIX] altCurrency settings keyboard flash

---

src/navigation/wallet-connect/components/WalletSelector.tsx
src/navigation/wallet/screens/GlobalSelect.tsx
src/navigation/wallet/screens/send/SendTo.tsx
src/store/scan/scan.effects.ts
src/store/wallet/effects/address/address.ts
src/store/wallet/utils/wallet.ts

1. Check address network of scanned address before showing wallet list in global send flow
2. Ensure user-defined wallet names are shown in the wallet selector
Also fixes a typescript error related to `KeyWalletsRowProps` missing a type argument

Send Fixes

---

src/lib/gift-cards/gift-card.ts
src/navigation/tabs/shop/components/GiftCardCreditsItem.tsx
src/navigation/tabs/shop/components/GiftCardDenomSelector.tsx
src/navigation/tabs/shop/components/GiftCardDenoms.tsx
src/navigation/tabs/shop/components/GiftCardItem.tsx
src/navigation/tabs/shop/gift-card/GiftCardStack.tsx
src/navigation/tabs/shop/gift-card/screens/BuyGiftCard.tsx
src/navigation/tabs/shop/gift-card/screens/GiftCardDetails.tsx
src/navigation/wallet/screens/Amount.tsx
src/navigation/wallet/screens/send/confirm/GiftCardConfirm.tsx

1. The international gift card experience is improved by displaying the currency symbol for all gift card related amounts (rather than the currency ISO code)
2. The virtual keyboard hides the decimal if the currency is JPY
3. Buy Gift Card screen now cleanly handles long lists of supported amounts for fixed denomination gift cards
4. The PR also ensures that all screens within the gift card purchase flow exist within the same stack so that popToTop() will always take the user back to the BuyGiftCard screen and then pop() will take them back to where they were before starting the purchase. This resolves an issue where the user would be taken back too far (to an onboarding screen) after purchasing a gift card.

International Gift Card Fixes

---

src/navigation/wallet/screens/KeyOverview.tsx

Currently, creating a multisig wallet, then accepting the invite with a different device, then going back to Key Overview, and then tapping on the newly created multisig wallet takes you back to the Copayers screen even though the invite has already been accepted. This can be confusing to users, especially if they are not aware that they need to pull to refresh on the Copayers screen to complete multisig wallet creation. This PR checks the status of the newly created multisig wallet on the Key Overview screen, and, if it is complete, navigates to the Wallet Details screen rather than the Copayers screen.

Check status of multisig wallet in Key Overview before navigating

---

src/navigation/tabs/shop/gift-card/screens/GiftCardDetails.tsx

Useful for gift card redemption flows that require the user to enter the amount of the gift card to be applied to the purchase.

Make gift card amount copyable

---

src/navigation/wallet/screens/AddWallet.tsx

Currently, even though the segwit checkbox is hidden on the Add Wallet screen for chains that don't support segwit, the segwit setting is still enabled for those chains by default. This PR fixes that.

Fix segwit default setting in Add Wallet screen

---

src/store/wallet/effects/send/send.ts

Changing the nonce in the confirmation view resets the value of the gas limit

[FIX] store gasLimit in txp object

---

src/navigation/wallet/screens/send/confirm/GiftCardConfirm.tsx

Navigating from the amount screen to the gift card confirm screen is causing a crash on iOS in release mode whenever the wallet selector is needed for a gift card purchase. This PR delays the wallet selector from showing on the confirm screen by 100ms which prevents the crash on my device.

Prevent crash during screen transition

---

src/navigation/tabs/home/components/advertisements/AdvertisementCard.tsx
src/navigation/wallet/screens/send/confirm/Confirm.tsx
src/navigation/wallet/screens/send/confirm/PayProConfirm.tsx
src/navigation/wallet/screens/send/confirm/Shared.tsx

Increases line item min-height to 60px to prevent collapsing on confirm screen resize.
Also fixes braze shop tab link handling.

Fix confirm screen line-item overlap on resize

---

src/navigation/wallet/screens/send/confirm/Confirm.tsx
src/navigation/wallet/screens/send/confirm/Memo.tsx
src/navigation/wallet/screens/send/confirm/PayProConfirm.tsx

1. Fix a border styling issue when the input is both empty and in edit mode
2. Ensure taps on the save and clear buttons are handled (rather than ignored) while the keyboard is open
3. On focus, scroll sufficiently to make sure entire memo input is above the keyboard (iOS only)

Optimize memo component

---

src/store/wallet/effects/rates/rates.ts

Avoid cannot read property `symbol` of undefined

[FIX] only save token rates if exists in tokens list

---

src/navigation/tabs/shop/ShopHome.tsx
src/navigation/tabs/shop/gift-card/GiftCardStack.tsx
src/navigation/wallet/WalletStack.tsx
src/navigation/wallet/screens/send/confirm/GiftCardConfirm.tsx
src/navigation/wallet/screens/send/confirm/PayProConfirmTwoFactor.tsx

1. Ensures that only a single tap is required to navigate to a gift card search result when the keyboard is open (currently two taps are required, with the first tap closing the keyboard)
2. Fixes a wonky stack reset that happens when purchasing a gift card with Coinbase by ensuring that the Coinbase 2fa screen is part of the GiftCardStack so that all screens in the checkout flow are all part of the same stack and therefore dismissed simultaneously

Gift card improvements

---

src/navigation/tabs/settings/components/Notifications.tsx
src/navigation/wallet/screens/WalletDetails.tsx
src/store/app/app.effects.ts

* Renew subscription for receive silent push notification and keep app active when it's open. 
* Debounce functions to avoid multiple calls
* Update list of transactions proposals when receive an update
* Ignore warning: Settings a time for long period of time (https://github.com/ably/ably-js/issues/749#issuecomment-455680414)

Fix: enable renew subscription for silent push notifications

---

src/store/wallet/effects/amount/amount.ts

Example:
50 DAI -> 
amountSat = 50000000000000000000
satToUnit = 1e-18
unitDecimals = 18
amountSat * satToUnit = 50.00000000000001
(amountSat * satToUnit).toFixed(unitDecimals) = 50.000000000000007105
With this workaround we take as `toFixed` the lesser between the number of decimals entered by the user (`amountDecimals`) and the `unitDecimals` to avoid results of unwanted decimal numbers

Ref: handle many decimals operations in ParseAmount

---

src/components/list/TransactionRow.tsx
src/navigation/wallet/WalletStack.tsx
src/navigation/wallet/screens/TransactionDetails.tsx
src/navigation/wallet/screens/WalletDetails.tsx

Also, this PR allows users to clear the memo entirely after it has been set (currently not supported) and ensures that the updated memo is instantly reflected in the parent wallet details view after being changed in the child transaction details view (without needing to manually pull to refresh to see the change)

Use memo component in Transaction Details

---

src/navigation/wallet/screens/TransactionProposalNotifications.tsx

How to reproduce the bug fixed by this PR:
1. Create a multisig proposal on the current master branch
2. Navigate to key overview
3. Tap the proposal notifications icon
4. Wait a while for the `isCacheKeyStale` check to return `true` (or comment out those lines in the code to force the logic to skipped)
5. Pull to refresh the proposal notifications screen (you’ll now see that the “created by” field will become a json object)
This PR fixes the issue and also ensures that only the statuses of keys with pending proposals are refreshed (not all keys)

Fix json copayer name

---

src/navigation/services/swap-crypto/screens/ChangellyCheckout.tsx

This portion of code was removed here by mistake apparently. So the swaps are not currently working: https://github.com/bitpay/bitpay-app/pull/303/files#diff-75567b38dc413b88bf0bfcd2f225e5bb12ffc0c2bc349405197b4b6cc2fe1f74L502

Fix: swap checkout publish and sign

---

src/store/wallet/wallet.reducer.ts

Reduces the amount of `WALLET` key data stored in `AsyncStorage` by ~90%.

Do not persist token data to device storage

---

src/store/transforms/transforms.ts

Currently, wallet transactions are persisted to storage despite being wiped again after refetching keys in the outbound redux-persist transform (which bloats storage unnecessarily). This PR ensures transactions are never persisted to device storage.

Clear wallet transaction history before saving keys to device storage

---

src/components/amount/Amount.tsx
src/constants/rate.ts
src/constants/wallet.ts
src/navigation/services/buy-crypto/screens/BuyCryptoOffers.tsx
src/navigation/tabs/home/HomeRoot.tsx
src/navigation/tabs/home/components/exchange-rates/ExchangeRateItem.tsx
src/navigation/wallet-connect/screens/WalletConnectIntro.tsx
src/navigation/wallet/components/RangeDateSelector.tsx
src/navigation/wallet/screens/AddWallet.tsx
src/navigation/wallet/screens/KeyOverview.tsx
src/navigation/wallet/screens/KeySettings.tsx
src/navigation/wallet/screens/PriceCharts.tsx
src/navigation/wallet/screens/WalletDetails.tsx
src/navigation/wallet/screens/send/confirm/Confirm.tsx
src/store/index.ts
src/store/rate/rate.actions.ts
src/store/rate/rate.models.ts
src/store/rate/rate.reducer.ts
src/store/rate/rate.types.ts
src/store/wallet/effects/currencies/currencies.ts
src/store/wallet/effects/rates/rates.ts
src/store/wallet/effects/status/status.ts
src/store/wallet/effects/transactions/transactions.ts
src/store/wallet/utils/wallet.ts
src/store/wallet/wallet.actions.ts
src/store/wallet/wallet.models.ts
src/store/wallet/wallet.reducer.ts
src/store/wallet/wallet.types.ts

Moves rates out of the `WALLET` storage key to a new dedicated `RATE` key to ensure that only the minimum amount of data is stored in the `WALLET` key to avoid running into OS-specific per-key storage limits.

Refactor rate storage

---

src/Root.tsx
src/navigation/wallet/WalletStack.tsx
src/navigation/wallet/screens/SendToOptions.tsx

* Go to Create -> New Key -> Swipe back (it goes to Home instead `Select an option` screen)
After fix:
* Swipe back is disabled on the `Select Currencies` screen.

Fix: prevent swipe back action returns to Home tab

---

src/navigation/tabs/shop/gift-card/screens/GiftCardDetails.tsx

Will make it easier to provide support for failed redemptions.

Include gift card invoiceId in failure message

---

src/components/virtual-keyboard/VirtualKeyboard.tsx

Docs: https://reactnative.dev/docs/pixelratio#get 
Device test: iPhone SE (Sim)

Fix: auto adjust number pad to screen size

---

package.json
src/Root.tsx
src/navigation/tabs/settings/components/Notifications.tsx
src/utils/hooks/useDeeplinks.ts
yarn.lock

This PR fixes FaceID loop.
https://reactnative.dev/docs/appstate#removeeventlistener
https://reactnative.dev/docs/linking#removeeventlistener

Fix: remove listener for appStatusChange to avoid duplicated events

---

src/navigation/scan/screens/Scan.tsx

on android devices 500 ms debounce time was not enough to avoid wrong behaviors

[RN-661]: Adding crypto address with scanning closes the contacts screen

---

src/navigation/wallet/screens/CurrencySelection.tsx

[FIX] show bitpay supported tokens first

---

android/app/src/main/AndroidManifest.xml

Getting error:
```
Manifest merger failed : Apps targeting Android 12 and higher are 
required to specify an explicit value for `android:exported` when 
the corresponding component has an intent filter defined. 
See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
```

Fix: added required "android:exported" for new targetSdkVersion (31)

---

src/components/list/CurrencySelectionRow.tsx
src/constants/SupportedCurrencyOptions.tsx
src/constants/config.ts
src/constants/currencies.ts
src/constants/tokens.ts
src/navigation/tabs/contacts/components/ContactIcon.tsx
src/navigation/tabs/contacts/screens/ContactsAdd.tsx
src/navigation/tabs/contacts/screens/ContactsDetails.tsx
src/navigation/wallet/screens/AddWallet.tsx
src/navigation/wallet/screens/CurrencySelection.tsx
src/navigation/wallet/screens/CurrencyTokenSelection.tsx
src/navigation/wallet/screens/GlobalSelect.tsx
src/navigation/wallet/screens/KeyOverview.tsx
src/navigation/wallet/screens/KeySettings.tsx
src/store/wallet/effects/create/create.ts
src/store/wallet/effects/currencies/currencies.ts
src/store/wallet/effects/import/import.ts
src/store/wallet/effects/rates/rates.ts

Fixes global selector
Order wallets by priority
Improve variable names

[REF] simplify adding new chains - 01

---

src/store/wallet/effects/import/import.ts

After accept terms when importing a wallet and back to Home view. Waiting for the import finish... Click on "ok", instead to open the new imported key, it asks to accept terms again.
ERROR:
https://user-images.githubusercontent.com/237435/194414872-178e633d-057f-4a57-b8b6-aee70ab66b3c.mov
FIXED:
https://user-images.githubusercontent.com/237435/194414117-7ce4bd19-c0ed-4bf6-9cc6-555182f0ae6a.mov

Fix: importing a first wallet on new installation asks to accept TermsofUsers twice

---

src/components/amount/Amount.tsx

Fix: keep position for swapButton (Amount View)

---

src/navigation/wallet/screens/send/confirm/Shared.tsx

Fix: show correct icon for recipients on Confirm Screen

---

src/components/avatar/Avatar.tsx
src/navigation/bitpay-id/screens/EnableTwoFactor.tsx
src/navigation/wallet/screens/send/confirm/Confirm.tsx
src/navigation/wallet/screens/send/confirm/Shared.tsx

Ensures the proper icon is shown when sending to a contact or an email on the confirm screen. Also copies the proper value to the clipboard when manually setting up 2fa.

Misc fixes

---

src/store/wallet/effects/create/create.ts

Tokens added from the `add wallet` option were not added to the wallet preferences, so when importing those tokens they were missing

[FIX] add tokens to preferences

---

src/store/wallet/effects/send/send.ts

needed for speedup and queed transaction... not really useful since matic transactions are confirmed pretty fast

[FIX] get nonce for matic

---

src/store/transforms/transforms.ts

It's applied when users already have a Matic Token in their app.
BEFORE the upgrade
AFTER the upgrade

FIX: use new Matic icon for matic_e after upgrade the app

---

src/navigation/coinbase/screens/CoinbaseAccount.tsx

Now Coinbase generates new BCH format address. 
So, it's not necessary to convert it from old format to new one, because bitcore returns error trying to do this function with a BCH address: 
```
Bitcore.Address(addressToTranslate)
```

Fix Coinbase: BCH deposit not working due to new format BCH address

---

locales/en/translation.json
src/components/amount/Amount.tsx
src/navigation/card/components/CardDashboard.tsx
src/navigation/services/buy-crypto/screens/BuyCryptoOffers.tsx
src/navigation/services/buy-crypto/utils/buy-crypto-utils.ts
src/navigation/wallet/screens/WalletDetails.tsx
src/store/buy-crypto/buy-crypto.effects.ts
src/store/buy-crypto/buy-crypto.models.ts

In this PR:
- Handle buy limits in Amount view
- Fix: reset real amount value when switch between currencies (Without this fix, you can enter a number, switch between currencies in the Amount view and the view will show 0, however the "Continue" button will still be enabled, since the actual value remains as it was)
- Fix: Added a warning message when trying to enter an amount bigger than max limit
- Fix: added translations to warning messages
- Fix: context: 'buyCrypto' from walletDetails and CardDashboard

Feat: handle buy limits in Amount view

---

src/store/wallet/utils/currency.ts

For example if we pass btc to the function `IsCustomERCToken`. 
The `currency` variable returns `btc_b`.
The next function BitpaySupportedCurrencies[`btc_b`] returns `false` ... and finally it's `!`, so it returns `true`. 
Finally the function `IsCustomERCToken` will return `true` for `BTC`
FIXED

Fix: check if custom token and show historic rates

---

src/navigation/tabs/home/HomeRoot.tsx
src/navigation/wallet/screens/KeyOverview.tsx
src/navigation/wallet/screens/TransactionProposalDetails.tsx
src/navigation/wallet/screens/TransactionProposalNotifications.tsx
src/navigation/wallet/screens/WalletDetails.tsx
src/store/wallet/wallet.models.ts

Include again all types of transaction proposals in badge count
new `Unsent Transactions` header that includes read only wallets txs (no sign available for this) and 1-1 transactions that need a sign ( created by a readonly wallet in another device)
Failed paypro transactions are listed in `Rejected` ( no sign available for this )

[REF] better handle of unsent transactions

---

src/api/coinbase/coinbase.constants.ts
src/api/coinbase/coinbase.types.ts
src/navigation/wallet/screens/send/confirm/DebitCardConfirm.tsx
src/navigation/wallet/screens/send/confirm/GiftCardConfirm.tsx
src/store/coinbase/coinbase.actions.ts
src/store/coinbase/coinbase.effects.ts
src/store/coinbase/coinbase.reducer.ts
src/store/coinbase/coinbase.types.ts
src/store/coinbase/index.ts
src/store/wallet/effects/send/send.ts

* Allow future support of Network selector (Coinbase: polygon or ethereum). For now, `ethereum` by default.
* Get correct `transactionCurrency` on creating Invoice for off-chain transactions.
Note 1: for Matic (Ethereum network) payments are disabled.
Note 2: Coinbase uses Ethereum network by default for all supported tokens.

Fix: create invoice for payments with Coinbase

---

src/lib/gift-cards/gift-card.ts
src/navigation/tabs/shop/ShopHome.tsx
src/navigation/tabs/shop/components/GiftCardCatalog.tsx
src/navigation/tabs/shop/components/MyGiftCards.tsx
src/navigation/tabs/shop/gift-card/screens/BuyGiftCard.tsx
src/navigation/tabs/shop/gift-card/screens/GiftCardDetails.tsx
src/store/bitpay-id/bitpay-id.effects.ts
src/store/shop/shop.effects.ts
src/store/shop/shop.models.ts

2 main scenarios to test:
1. On a fresh install, log in with a BitPay account that has gift card purchases associated with it (upon logging in, your associated gift cards will appear at the top of the shop tab)
2. While logged in with your BitPay account on one device, purchase a gift card on a different device (or in the BitPay browser extension) that is also logged in to the same BitPay account as the first device. Return to the first device, and pull to refresh on the shop tab. The gift card you purchased on the second device will now appear at the top of the shop tab on the first device.

Implement gift card syncing

---

src/navigation/tabs/settings/components/Notifications.tsx
src/store/wallet/effects/transactions/transactions.ts

[RN-770]: fix fiat rate str in txp view 

---

src/navigation/services/buy-crypto/BuyCryptoStack.tsx
src/navigation/services/buy-crypto/screens/BuyCryptoRoot.tsx
src/navigation/tabs/home/components/advertisements/AdvertisementCard.tsx
src/navigation/tabs/home/components/offers/OfferCard.tsx
src/navigation/wallet/screens/CurrencyTokenSelection.tsx
src/store/scan/scan.effects.ts
src/utils/hooks/useDeeplinks.ts
src/utils/hooks/useLogger.ts

With the AppsFlyer SDK in place, we can now handle OneLink links, however any embedded deeplink inside a OneLink does not get handled by the Navigation Container and the linking configuration we have configured. Added logic so that if our custom handling doesn't handle the passed in URL, then default to the Navigation Container deeplinking.

Backwards compatible deeplinks

---

src/navigation/wallet/components/RecoveryPhrase.tsx
src/store/wallet/effects/import/import.ts

1. Handles and displays key import errors along with the exact error code
2. Starts the import immediately (rather than waiting on the user to tap "GOT IT" on the "import in progress" action sheet)

Improve key import flow

---

src/store/wallet/effects/import/import.ts

It fixes error: `Rate not found for currency: busd, matic, etc.` after import key.

FIX [RN-783]: force get rates for new users after first import

---

index.js
ios/Podfile.lock
package.json
yarn.lock

This PR enables freeze mode for react-native-screens which freezes the subtree for screens that are not visible, improving performance. 
https://github.com/software-mansion/react-freeze#quick-start-with-react-navigation-react-native-
One way to test the performance gain is to try switching theme with the enableFreeze flag true and false.

[FEAT] react-native-screens freeze

---

ios/BitPayApp/BitPayAppDebug.entitlements
ios/BitPayApp/BitPayAppRelease.entitlements

This PR adds associated domains to the iOS entitlements to support wrapped universal links.

Add domains for wrapped universal links (iOS)

---

src/store/wallet/utils/decode-uri.ts
src/store/wallet/utils/validations.ts

Handle payment protocol URIs in the format: `bitpay:?r=https://bitpay.com/i/4brRCvJxXrhgaRvmVp7ghj` 
(and `bitpay:?r=https://test.bitpay.com/i/4brRCvJxXrhgaRvmVp7ghj` for testnet invoices)

Handle BitPay payment protocol URIs

---

src/components/form/BoxInput.tsx
src/navigation/auth/screens/TwoFactor.Auth.tsx
src/navigation/auth/screens/TwoFactor.Pair.tsx

`keyboardType` was always undefined for iOS devices.

FIX[RN-801]: set input type to show keyboard in 2FA screen

---

src/navigation/services/buy-crypto/components/PaymentMethodModal.tsx
src/navigation/services/buy-crypto/components/terms/WyreTerms.tsx
src/navigation/services/buy-crypto/constants/BuyCryptoConstants.tsx
src/navigation/services/buy-crypto/screens/BuyCryptoOffers.tsx
src/navigation/services/buy-crypto/screens/BuyCryptoRoot.tsx
src/navigation/services/buy-crypto/utils/buy-crypto-utils.ts
src/navigation/services/buy-crypto/utils/wyre-utils.ts
src/navigation/tabs/settings/components/ExternalServices.tsx
src/navigation/tabs/settings/external-services/screens/WyreSettings.tsx
src/store/buy-crypto/buy-crypto.effects.ts

Reverts bitpay/bitpay-app#622
It was recently decided that the Wyre integration will continue to work in our app, since it will continue to provide its services

Revert "Removes Wyre integration from supported buy crypto exchanges"

---

ios/BitPayApp/AppDelegate.m
src/Root.tsx

Currently, deep links from braze notifications are ignored on app launch (when the app is not yet running before a push notification is tapped). This PR fixes the issue.

get braze ios deep links working on app launch

---

src/store/wallet/effects/import/import.ts

To trigger this error enter the 12 words phrase and set an incorrect passphrase in the advanced option

[REF] handle wallet_does_not_exist err correctly

---

src/navigation/tabs/settings/about/screens/SessionLog.tsx
src/store/app/app.effects.ts
src/store/log/log.actions.ts
src/store/log/log.reducer.ts
src/store/log/log.types.ts
src/store/transforms/transforms.ts
src/store/wallet/wallet.reducer.ts

To persist a log for 7 days, wrap any logging call (e.g. `LogActions.error('message')`) in a `LogActions.persistLog()` call. Persisted logs appear in the new "Previous Sessions" section of the Session Log after the app is closed and reopened.
Example in the PR: https://github.com/bitpay/bitpay-app/pull/649/files#diff-26b3bdd77ae5fe7a321c95fab44e327692df02238a4928be27e73b55f4c815aaR62

Implement log persistence

---

locales/de/translation.json
locales/en/translation.json
locales/es/translation.json
locales/fr/translation.json
locales/ja/translation.json
locales/nl/translation.json
locales/pt/translation.json
locales/ru/translation.json
locales/zh/translation.json
src/navigation/services/buy-crypto/screens/BuyCryptoOffers.tsx
src/navigation/services/buy-crypto/screens/BuyCryptoRoot.tsx
src/navigation/services/swap-crypto/screens/SwapCryptoRoot.tsx
src/store/external-services/external-services.effects.ts
src/store/external-services/external-services.types.ts
src/store/wallet/effects/errors/errors.ts

Remote config example from BWS:
```   
services: {
buyCrypto: {
disabled: false,
moonpay: {
disabled: false,
removed: false
},
simplex: {
disabled: false,
removed: true
},
wyre: {
disabled: true,
disabledMessage: 'Wyre is out of service.',
removed: false
}
},
swapCrypto: { 
disabled: false,
changelly: {
disabled: false,
removed: false
}
},
},
```

Feat: Remote config for buy and swap

---

src/store/scan/scan.effects.ts
src/store/wallet/utils/validations.ts

Currently invoice web url scan handling only works if `id` is the first query param in the url. This PR ensures scan handling works regardless of the order the query params in the web url.

Improve invoice web url scan handling

---

src/Root.tsx
src/store/app/app.actions.ts
src/store/app/app.reducer.ts
src/store/app/app.types.ts

This definitely improves the app performance ( we were saving the currentRoute everytime we move to another view sometimes with huge params ) and fix the `data base or disk is full` for android

[REF] remove current route from store

---

src/navigation/wallet/screens/TransactionProposalDetails.tsx
src/store/wallet/effects/transactions/transactions.ts

For showing the matic_eth wallet in the header we need bws changes. But, I think this way actually makes sense and lgtm ( showing the associated eth wallet )

[FIX] erc20 pending proposals view

---

src/navigation/wallet/screens/send/confirm/DebitCardConfirm.tsx

Selecting a matic token should create a matic invoice

[FIX] create topup invoice for matic tokens

---

src/navigation/services/buy-crypto/screens/BuyCryptoOffers.tsx

Moonpay only accepts EUR as a base currency for SEPA payments.
This PR forces to use EUR if the selected fiat currency of the app is other than EUR.

Fix: Moonpay SEPA bank transfer getQuote

---

src/navigation/wallet/screens/send/confirm/Confirm.tsx
src/store/wallet/effects/send/send.ts

Since we are creating the transaction proposal before moving to the confirm view ( the only view that had the RBF option ) now checking for the `enableReplaceByFee` flag is needed in `createProposalAndBuildTxDetails`

[REF] change default for RBF flag

---

src/navigation/wallet/screens/send/SendTo.tsx
src/navigation/wallet/screens/send/confirm/PayProConfirm.tsx
src/navigation/wallet/screens/send/confirm/Shared.tsx
src/store/scan/scan.effects.ts
src/store/shop/shop.models.ts
src/store/wallet/utils/wallet.ts

* Do not show Coinbase wallets if it's not enabled for pay BitPay Invoice
* Removes duplicated http request for BitPay Invoice
* Show generic message if there're no wallets for selected BitPay Invoice

Ref: check threshold for Coinbase payments. Show message if no wallet available. Single request for Invoice data

---

src/navigation/wallet/screens/CurrencySelection.tsx
src/store/wallet/effects/currencies/currencies.ts
src/store/wallet/wallet.reducer.ts

Reverts bitpay/bitpay-app#747
In order to decrease the number of http requests that get a long list of tokens (no necessary all the time), we made this PR adding that information to the persist storage. But on Android there's a limit for storing data in the DB (6MB). We're getting this error: 
```
Error storing data [Error: database or disk is full (code 13 SQLITE_FULL[13])]
```
Solution would be doing the http request only where it's necessary. For the moment, we're going to keep doing request and no storing data in persist storage.
References:
https://github.com/react-native-async-storage/async-storage/issues/427

Revert "Fix: speed up app startup using cached rates"

---

src/navigation/services/buy-crypto/BuyCryptoStack.tsx
src/navigation/services/buy-crypto/components/PaymentMethodModal.tsx
src/navigation/services/buy-crypto/constants/BuyCryptoConstants.tsx
src/navigation/services/buy-crypto/screens/BuyCryptoOffers.tsx
src/navigation/services/buy-crypto/screens/BuyCryptoRoot.tsx
src/navigation/services/buy-crypto/utils/buy-crypto-utils.ts
src/store/buy-crypto/buy-crypto.effects.ts
src/store/scan/scan.effects.ts
src/store/wallet/utils/validations.ts

In this PR I add the deeplinks handler with the possibility of presetting a partner so that it is the only one to be displayed.
I also added the possibility of presetting amount and coin if necessary
Examples:
```
bitpay://buyCrypto?partner=moonpay&coin=usdc&chain=eth&amount=100
bitpay://buyCrypto?partner=ramp&coin=btc&amount=200
bitpay://buyCrypto?partner=simplex
bitpay://buyCrypto?partner=wyre&amount=500
```

Feat: buyCrypto deeplink handling

---

android/app/src/main/java/com/bitpay/wallet/MainActivity.java

It also happens with any deeplinks (BitPay Card link, etc)
https://stackoverflow.com/questions/45676629/how-can-we-remove-deep-link-data-from-intent

Fix: prevent multiple redir after link Coinbase account (only Android)

---

locales/en/translation.json
locales/es/translation.json
src/components/list/TransactionProposalRow.tsx
src/navigation/wallet/components/BalanceDetailsModal.tsx
src/navigation/wallet/components/MultipleOutputsTx.tsx
src/navigation/wallet/screens/TransactionProposalDetails.tsx
src/navigation/wallet/screens/TransactionProposalNotifications.tsx
src/navigation/wallet/screens/WalletDetails.tsx

- Update TxpRow to show a more accurate label for contacts or multiple recipients
- Fix label and dropdown arrow in MultipleOutputs Tx
- Show merchant domain instead of address for pending Txps
- Do not show fiat balances for testnet in balanceDetailsModal

Feat: update notifications view and Txps

---

src/navigation/services/buy-crypto/screens/BuyCryptoOffers.tsx
src/store/buy-crypto/buy-crypto.models.ts
src/store/buy-crypto/effects/moonpay/moonpay.ts

By implementing this function, we will obtain the limits for the selected values, prior to performing the getQuote, thus avoiding reporting continuous error events when users want to buy limit amounts.
This PR needs: https://github.com/bitpay/bitcore/pull/3593

Feat: Moonpay getCurrencylimits implemented

---

src/store/scan/scan.effects.ts

Fix: goToPaypro confirm when "Pay In Wallet" of an invoice is clicked

---

src/components/list/InputsRow.tsx
src/navigation/wallet/screens/SelectInputs.tsx

- Show fiat amounts in select inputs view: I added the fiat values of each input and the total, in the same selection view. Currently this is not displayed and for certain use cases it is cumbersome, since the only time you can see the fiat equivalents is in the final confirm view
- Some minor UI fixes

Feat: show fiat amounts in select inputs view

---

src/navigation/tabs/shop/components/GiftCardCatalog.tsx
src/navigation/tabs/shop/components/ShopCarouselList.tsx
src/navigation/tabs/shop/components/ShopOnline.tsx
src/store/wallet/effects/send/send.ts

This PR restores the ability to vertically scroll the `gift cards` and `shop online` tabs and fixes some carousel spacing/height issues.
Also gets Coinbase payments working for invoices that don't yet have a transaction currency selected (e.g. mobile transfer).

Ensure shop tab works well with new carousel package

---

src/navigation/wallet/screens/send/confirm/Confirm.tsx
src/navigation/wallet/screens/send/confirm/Shared.tsx
src/store/wallet/effects/send/send.ts

* Fixed percent of total amount for ETH or MATIC 
* Added thousands separator for "Gas Limit" field.

Fix: percentage of total amount on confirm screen

---

src/store/shop/shop.models.ts
src/store/wallet/effects/send/send.ts

Choosing any other currency than usd here https://bitpay.com/demos/ results in incorrect rate calculations

[FIX] rate calculation when creating using crypto amount instead of usd

---

src/store/coinbase/coinbase.effects.ts

Coinbase stopped support for some regions and removed many user accounts. For this case, the app was trying to reconnect every time with error. This PR disconnect the account directly.

Fix: unlink Coinbase for invalid accounts

---

package.json
src/navigation/tabs/shop/gift-card/screens/GiftCardDetails.tsx

Currently, if redeem instructions contain HTML, the HTML tags are rendered as plain text which looks messy and hard to read. This PR ensures that redeem instructions containing HTML render properly.

properly render redeemInstructions that contain html

---

src/store/wallet/effects/amount/amount.ts
src/utils/helper-methods.ts

In this way, we are no longer dependent on the CWC listing, as we have the accuracy values anyway.

[REF] move formatAmount function from bwc to helper methods

---

src/navigation/services/buy-crypto/screens/BuyCryptoOffers.tsx
src/navigation/tabs/settings/external-services/screens/SardineDetails.tsx

In this PR:
- When the user clicks "Buy", a loading spinner will be displayed until the browser opens to display the checkout page.
- The other "Buy" buttons of the other exchanges will be disabled while the browser for the selected exchange is opened.
- Added a limit to decimals displayed in the offer

Fix: buy crypto UI adjustments

---

src/navigation/wallet/screens/BackupOnboarding.tsx

Steps to reproduce the error:
1) Go to Settings -> Wallets & Keys -> (Select a Key) -> Enable: "Request Encrypt Password" -> Enter a new password
2) Go to Backup -> Write Down Recovery Phrase -> Enter your password
3) Go back and Disable "Request Encrypt Password"
4) Enter again in Backup -> Write Down Recovery Phrase
At this point the encrypt password will be requested again despite having been previously disabled. (Entering any password will be considered valid and you will enter the backup view).

Fix: backup encrypt pass request

---

src/navigation/wallet/screens/WalletDetails.tsx

* Adds `leading: true`
* Also revert https://github.com/bitpay/bitpay-app/pull/932

Fix: loading history when it is empty and infinite scrolling

---

src/navigation/services/components/ToWalletSelectorModal.tsx
src/navigation/wallet/screens/AddWallet.tsx
src/navigation/wallet/screens/CreateMultisig.tsx
src/store/wallet/effects/create/create.ts
src/store/wallet/utils/currency.ts

Only set the `useNativeSegwit` option for coins that support segwit when creating a new wallet.

[FIX] use `useNativeSegwit` wallet creation option properly

---

src/components/form/BoxInput.tsx
src/navigation/tabs/contacts/screens/ContactsAdd.tsx
src/navigation/wallet/screens/VerifyPhrase.tsx

Removes the background and prevents the icon from overlapping the text

Fix: box input icons

---

src/Root.tsx
src/components/modal/biometric/BiometricModal.tsx
src/components/modal/pin/PinModal.tsx
src/constants/device-emitter-events.ts
src/utils/hooks/useDeeplinks.ts

How to reproduce the error:
iOS:
Enable the PIN/Biometric lock method:
- If the app is closed (Not in the background) and you click on a deeplink: There is a race between the lock modal and the navigation to the destination page. If the modal is showed before the navigation, then the app crashes and needs to restart.
Proposed solution: Wait for the lock modal to be successfully dismissed before performing the navigation.
- If the app is in the background there are 3 possible cases to take into account:
1) It has been minimized more than 20 seconds ago since the last unlock (`lockAuthorizedUntil`). So when you click on a deeplink, you return to the app, it shows the lock modal and a case similar to the previous one happens, in which a race occurs between the lock modal and the link …

Fix: deeplinks handling when lock method is enabled

---

src/navigation/tabs/home/components/quick-links/QuickLinksCard.tsx
src/navigation/tabs/shop/components/ShopCarouselList.tsx
src/navigation/wallet/screens/send/confirm/BillConfirm.tsx
src/navigation/wallet/screens/send/confirm/PayProConfirm.tsx

Prevent `onPress` handler from firing while scrolling carousels horizontally on iOS.
Prevent crash on iOS when dismissing payment success modals on PayPro and Bill confirm screens.

Ensure iOS build works well with new react-navigation

---

src/navigation/coinbase/CoinbaseGroup.tsx
src/navigation/coinbase/components/CoinbaseDashboard.tsx
src/navigation/coinbase/screens/CoinbaseAccount.tsx
src/navigation/tabs/shop/gift-card/screens/GiftCardDetails.tsx
src/navigation/wallet/screens/send/confirm/BillConfirm.tsx
src/navigation/wallet/screens/send/confirm/GiftCardConfirm.tsx
src/navigation/wallet/screens/send/confirm/PayProConfirm.tsx
src/navigation/wallet/screens/send/confirm/PayProConfirmTwoFactor.tsx
src/store/wallet/effects/send/send.ts
src/utils/helper-methods.ts

1. Better handles common send errors in bill pay, gift card, and paypro confirm screens
2. Fixes Coinbase 2fa screen (ensures all content is displayed inside a SafeAreaView)
3. Falls back to displaying a claim link for a gift card that comes with a barcode when the barcode fails to generate
4. Fixes offchain Coinbase payments with ERC20 tokens
5. Improves reliability of gift card barcode scanning when using dark mode

Confirm, Coinbase and Gift Card Screen Fixes

---

src/navigation/bitpay-id/BitpayIdGroup.tsx
src/navigation/bitpay-id/screens/EnableTwoFactor.tsx
src/navigation/bitpay-id/screens/ReceiveSettings.tsx
src/navigation/bitpay-id/screens/ReceivingEnabled.tsx
src/navigation/bitpay-id/screens/TwoFactorEnabled.tsx

This PR fixes the following BitPay ID settings features:
1. 2FA enabling/disabling
2. Managing "Receive via Email Address" wallet addresses

Get BitPay ID settings working well with new navigation

---

src/navigation/tabs/settings/general/screens/customize-home/CustomizeHome.tsx

* Currently the Home Layout (Carousel or List view) only works in English.
* Smoother goBack function after click on Save Layout.

Fix: save selected Home Layout using the app in foreign language

---

src/components/currency-image/CurrencyImage.tsx
src/navigation/bitpay-id/screens/ReceiveSettings.tsx
src/navigation/tabs/shop/ShopHome.tsx
src/navigation/wallet/screens/send/confirm/Shared.tsx

This PR ensures users are taken to the new top-level bill pay tab when tapping the old "Pay Bills" subtab in the Shop tab.

Fix Shop tab "Pay Bills" behavior and fix token icons

---

src/navigation/tabs/settings/general/screens/customize-home/CustomizeHome.tsx

The Tab Navigator can be a bit unreliable when it comes to programmatically selecting an initial nested tab that isn't the first tab. This PR includes a workaround for this issue by ensuring that the initially selected tab is always listed first in `CustomizeHome.tsx`.

Fix initial tab selection in CustomizeHome.tsx

---

src/navigation/wallet/screens/WalletDetails.tsx
src/store/wallet/effects/transactions/transactions.ts

Currently the list of transactions in Wallet Details only displays the most recent 25 transactions. Scrolling to the bottom of the list fetches the next 25 transactions but never actually renders them. This PR gets infinite scroll working properly for Wallet Details transaction history by actually rendering the next 25 transactions fetched at the bottom of the list and also wraps all transaction item components with `useCallback`.

Fix transaction history infinite scroll

---

src/Root.tsx
src/store/app/app.reducer.ts

Way to reproduce the issue: Leave the app open for more than 20 seconds, in which case the `lockAuthorizedUntil` will have expired. When closing and reopening the app, the value of `lockAuthorizedUntil` was not removed, so after successfully passing the unlock to open the app, it interprets that `lockAuthorizedUntil` has expired and asks for it again.
The solution I propose is to add `lockAuthorizedUntil` to the `appReduxPersistBlackList`

Fix: prevent unlock modal from being displayed twice in a row when the app is open

---

index.js
package.json

https://github.com/a7ul/react-native-exception-handler 
Persist log for exceptions after the app crash.

Feat: global error handler to capture uncaught exceptions. Adds new event

---

android/app/src/main/java/com/bitpay/wallet/MainApplication.java
android/app/src/main/java/com/bitpay/wallet/UserAgentClientFactory.java
android/app/src/main/java/com/bitpay/wallet/UserAgentInterceptor.java

Currently the default user agent for android devices appears to be `okhttp/4.9.2`. This PR sets it to `BitPayApp/<version> Android`.

Specify user agent on android devices

---

src/store/analytics/analytics.effects.ts
src/store/bitpay-id/bitpay-id.effects.ts
src/utils/braze.ts

It helps to force subscription to (silent) push notifications after login or logout BitPay ID

Fix: renew Braze EID for (silent) push notifications

---

src/navigation/auth/screens/VerifyEmail.tsx
src/store/bitpay-id/bitpay-id.effects.ts

This PR ensures the email verification flow continues to work after the app is closed and reopened after initial account creation. Closing and reopening the app causes a new unauthenticated session to be created which currently causes the email verification link request to fail with a 401. This PR fixes the issue by requesting that the user log in again if they no longer have an authenticated session.

Fix email verification flow

---

src/navigation/tabs/shop/ShopHome.tsx
src/styles/tabNavigator.ts

Now that users have had enough time to get used to the location of the new top-level bill pay tab, we can remove the "Pay Bills" sub tab from the shop tab.

Remove "Pay Bills" sub tab from shop tab

---

src/navigation/services/buy-crypto/screens/BuyCryptoOffers.tsx
src/navigation/services/sell-crypto/screens/SellCryptoRoot.tsx

From Moonpay team:
"I noticed upon testing earlier that you are showing the "Enter Wallet Address" screen.
We know through our data that this can often cause CVR issues, as it adds an extra screen to the funnel and can confuse users.
To avoid this, please stop using the showWalletAddressForm param."

Ref: do not show wallet address form on moonpay checkout

---

src/constants/config.ts
src/lib/bwc.ts
src/navigation/tabs/settings/general/screens/Theme.tsx
src/store/app/app.reducer.ts
src/store/bitpay-id/bitpay-id.reducer.ts
src/store/card/card.reducer.ts
src/store/shop/shop.reducer.ts

Fixes regtest related typescript errors, and makes it possible to test payment protocol payments on regtest in test mode by specifying the following variables in `.env.development`:
`TEST_MODE_NETWORK=regtest`
`REGTEST_BASE_BITPAY_URL`
`PAYPRO_TRUSTED_KEYS`

Support regtest paypro payments

---

src/store/wallet/effects/paypro/paypro.ts

Currently errors that happen inside of the `HandlePayPro` method are swallowed. This PR ensures they bubble up to the user and are displayed using the standard error info sheet. Also includes the `FAILURE` status in the gift card redemption failure status list.

Display HandlePayPro errors

---

src/components/blur/Blur.tsx

* It's needed when "Reduce Transparency" on iPhone is ON.

Fix: match theme fallback color for BlurView

---

src/navigation/tabs/settings/components/Notifications.tsx

This PR only removes the `OnAppStateChange` that is unnecessary since the app resubscribe to push notifications in an interval.

Fix: avoid to read old value for enable/disable push notifications when resume the app from background

---

src/lib/gift-cards/gift-card.ts
src/store/bitpay-id/bitpay-id.effects.ts
src/store/shop/shop.effects.ts

This will improve the gift card experience by proactively fetching gift card redemption information for the 3 most recent gift card purchases immediately after initial gift card sync completes after a user logs in to their account.

Redeem 3 newly synced gift cards after login

---

src/navigation/bitpay-id/utils/bitpay-id-utils.ts

Example: usdc_c_e
Coin: usdc_c
Chain: eth

Fix: get coin and chain from symbols with multiple underscores

---

src/store/wallet/effects/transactions/transactions.ts

Filter TX with no effects for ERC20 tokens

Fix: transaction history for arb/base/op tokens

---

src/navigation/card/screens/CardHome.tsx
src/navigation/tabs/TabScreenErrorFallback.tsx
src/navigation/tabs/home/HomeRoot.tsx
src/navigation/tabs/shop/ShopHome.tsx
src/navigation/tabs/shop/ShopStack.tsx
src/navigation/tabs/shop/bill/screens/BillsHome.tsx

Currently, if one of the top-level tabs crashes, the entire app crashes. This PR ensures that only the affected tab crashes and that an error screen is shown its place. To test this PR, throw an error in any of the top-level tabs.

Error Fallback Screen for Top-Level Tabs

---

src/navigation/auth/screens/VerifyEmail.tsx

This will prevent users from accidentally navigating back to the create account screen via the android hardware back button after already having successfully created an account.

Disable hardware back button on verify email screen

---

src/components/modal/transact-menu/TransactMenu.tsx

Currently the "Buy Gift Cards" button is cut off in the the `TransactMenu` on shorter devices like the iPhone SE. This PR enables scrolling of the `TransactMenu` on short screens to ensure all list items can be accessed.

Fix cut off "Buy Gift Cards" button in TransactMenu on short screens

---

src/navigation/tabs/TabScreenErrorFallback.tsx
src/navigation/tabs/home/HomeRoot.tsx

1. Displays the javascript stack on the fallback screen, which includes the line number where the uncaught exception happened
2. Makes it possible to navigate to settings from the home fallback screen via a cog icon in the top left corner

Improve Tab Screen Error Fallback

---

declarations.d.ts
src/lib/Braze/index.ts
src/navigation/onboarding/screens/OnboardingStart.tsx
src/store/analytics/analytics.effects.ts
src/store/app/app.actions.ts
src/store/app/app.effects.ts
src/store/app/app.reducer.ts
src/store/app/app.types.ts
src/store/bitpay-id/bitpay-id.effects.ts

* Generate new EID when anonymous user allow Push Notifications
* Migrate current EID when user login BitPay and remove old EID. (Avoid duplicated profiles)
* New event "Application Installed" (similar First App Opened)
* Continue tracking when "Log Out User success" using same EID as logged
Required: API key for merge and delete functions.

Ref: migrate tracking data from anonymous users

---

src/navigation/services/sell-crypto/screens/SellCryptoRoot.tsx
src/navigation/services/swap-crypto/screens/SwapCryptoRoot.tsx
src/navigation/services/swap-crypto/utils/changelly-utils.ts
src/navigation/wallet/screens/GlobalSelect.tsx

Due to this error, ETH Optimism/Arbitrum/Base wallets were displayed when they were not necessarily supported by external services. This caused for example that the "Sell" withdrawal method selector to be empty when ETH (Optimism) was selected.

Fix: sell/swap unsupported coins in selector

---

src/components/chain-search/ChainSearch.tsx
src/components/list/GlobalSelectRow.tsx
src/components/modal/chain-selector/ChainSelector.tsx
src/navigation/services/swap-crypto/screens/SwapCryptoRoot.tsx
src/navigation/services/swap-crypto/utils/changelly-utils.ts
src/navigation/tabs/settings/external-services/screens/SwapHistorySelector.tsx

This PR fixes:
- The minimum is now handled in Amount View, if the pair selected by the user is only supported by Changelly
Thorswap no longer maintains an endpoint to consult the limits of the selected pair, so if Thorswap is enabled, in the amount selector I do not show minAmount (maxAmount is the available funds of the wallet). I only show minAmount and maxAmount if Changelly is the only exchange enabled for swap.
- "USD Coin" was being renamed as "Ethereum" in the swap selectors, this error had two origins: The first is that Changelly decided to change the name of "USD Coin" to "USD Coin Ehtereum Chain", and in turn we had a line in the GlobalSelector that stepped on every string that contains the word Ethereum for "Ethereum"
- Filters were not working for swap crypto. It was due to …

Fix: swap crypto fixes

---

src/store/bitpay-id/bitpay-id.effects.ts

This PR adds error handling for user analytics initialization logic so that it doesn't break user store initialization.

Fix: prevent create account form redirecting to login screen

---

src/navigation/wallet/screens/TransactionProposalNotifications.tsx
src/store/wallet/effects/transactions/transactions.ts

* Temporal solution: shouldn't get 2 transactions for sending Token that pay fees with ETH.
BEFORE
AFTER

Fix: prevent showing txp duplicated

---

src/navigation/services/components/ApproveErc20Modal.tsx
src/navigation/wallet/components/SendingToERC20Warning.tsx
src/store/moralis/moralis.effects.ts

In this PR I also fixed the "View contract" link of the spender address

Ref: prevent cached responses for token allowance requests

---

src/store/wallet/effects/transactions/transactions.ts

When first address from `outputs` is `false`, it's a transaction with OP_RETURN (amount: 0). 
```
addressTo: 'false',
outputs: [
{
address: 'false',
amount: 0,
message: null,
encryptedMessage: null
},
{
address: 'bxxx',
amount: 1000000,
message: '<ECANNOTDECRYPT>',
encryptedMessage: '{xxx}'
}
]
```

Fix: TX history for Thorswap transactions (OP_RETURN)

---

src/Root.tsx
src/components/modal/import-ledger-wallet/ImportLedgerWalletModal.tsx
src/navigation/tabs/home/HomeRoot.tsx
src/navigation/wallet/screens/KeyOverview.tsx
src/store/app/app.effects.ts
src/store/wallet/effects/create/create.ts
src/store/wallet/effects/import/import.ts
src/store/wallet/effects/init/init.ts
src/store/wallet/effects/status/status.ts

I also include a verified_contract filter to minimize possible spam tokens
Fix: The detectAndCreateTokens function was running only for the first detected EVM wallet. With this fix all EVM wallets for the key will be checked.
I updated the Key overview to update the status every time the user enters the view
I added more logs

Feat: run detect and create tokens when new block arrives

---

src/navigation/wallet/screens/KeySettings.tsx
src/navigation/wallet/screens/UpdateKeyOrWalletName.tsx

Fixes: 
- The placeholder is not auto-filling in the Account name change form.
- When a new Key name is saved, it is not updated where names are displayed in settings, for example in the "Export wallet" option

Fix: key updates when there are changes in settings

---

src/navigation/wallet/screens/WalletDetails.tsx

It appears that using a `FlashList` within the `ListHeaderComponent` of another `FlashList` causes the `FlashList` inside of the `ListHeaderComponent` to...well...flash during scrolling. This PR gets the `ListHeaderComponent` containing transaction proposals to use a `FlatList` again (instead of a `FlashList`) to eliminate flashing during scrolling.

[FIX] Flashing transaction proposals on scroll

---

src/navigation/wallet/screens/AccountDetails.tsx
src/store/wallet/effects/create/create.ts
src/store/wallet/utils/wallet.ts

This workaround is for the app to check if the detected funded token has already been created previously, and if for some reason it was not added to the AssociatedWallet.tokens, then it adds it there and does not create it again.
It also adds a uniqBy(..., id) function so that only one wallet of said token is shown in account details, in case the same token has already been created more than once previously.

Fix: check existing tokens before auto-create

---

src/navigation/wallet/screens/send/confirm/GiftCardConfirm.tsx
src/store/shop/shop.actions.ts
src/store/shop/shop.effects.ts
src/store/shop/shop.reducer.ts
src/store/shop/shop.types.ts

Alerts the user that the expired coupon is no longer available and allows them to complete their purchase without the coupon if they so choose.

Fix: handle expired coupons

---

src/navigation/wallet/screens/AccountDetails.tsx
src/navigation/wallet/screens/AddingOptions.tsx
src/store/app/app.effects.ts

- This update fixes the issue with adding an EVM account to keys that don’t yet have an EVM wallet.
- Updated option text description.
- Corrected the navigation to direct to Account Settings instead of Key Settings from the account view.
- Added CREATING_KEY to the list of ongoingprocess that will not be dismissed after 60 seconds

[FIX] account creation on key's without evm wallets

---

src/store/app/app.effects.ts

New SDK doesn't require to call `getContentCards`.
Event `CONTENT_CARDS_UPDATED` listen for updates as a result of card refreshes. 
Keep `requestContentCardsRefresh()` to refresh manually if getting 0 cards.

Fix: prevents call CONTENT_CARDS_UPDATED event ad infinitum

---

src/navigation/coinbase/screens/CoinbaseAccount.tsx
src/navigation/services/buy-crypto/screens/BuyCryptoRoot.tsx
src/navigation/services/swap-crypto/components/FromWalletSelectorModal.tsx
src/navigation/services/swap-crypto/screens/SwapCryptoRoot.tsx
src/navigation/wallet/screens/PaperWallet.tsx

Safe area insets are now configured inside of the SheetModal component, so no need to also define them on each GlobalSelectContainer instance.

Fix: excessive top padding for global select component on iOS

---

ios/BitPayApp/Info.plist
ios/Podfile

Location data is getting from `https://bitpay.com/location/ipAddress`. App doesn't require location permission.

Fix: remove unused location system permission

---

src/constants/config.ts

This is part of the migration from testnet3 -> testnet4 for both BCH and BTC.

[REF] Update BTC & BCH testnet labels to Testnet4

---

src/components/list/AssetsByChainRow.tsx

Fixed error:
```
VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead. Error Component Stack
```

Fix: replaces Flatlist by Flashlist

---

src/navigation/tabs/contacts/screens/ContactsDetails.tsx
src/navigation/wallet/screens/GlobalSelect.tsx
src/store/wallet/utils/wallet.ts

* For Matic (Polygon), the app uses `CurrencyAbbreviation` to show it as POL instead of MATIC. 
* The result is that some External Service (like Coinbase) doesn't find any `matic` wallet if it checks against CurrencyAbbreviarion (that's `pol`).

Fix: GlobalSelect should check coin/chain from credentials instead CurrencyAbbreviation

---

src/components/modal/bottom-notification/BottomNotification.tsx
src/constants/BWCError.ts
src/navigation/services/sell-crypto/screens/MoonpaySellCheckout.tsx
src/navigation/services/sell-crypto/screens/SimplexSellCheckout.tsx
src/navigation/services/swap-crypto/screens/ChangellyCheckout.tsx
src/navigation/services/swap-crypto/screens/SwapCryptoApproveErc20.tsx
src/navigation/services/swap-crypto/screens/ThorswapCheckout.tsx
src/navigation/wallet/components/ErrorMessages.tsx
src/navigation/wallet/components/ReceiveAddress.tsx
src/navigation/wallet/screens/TransactionProposalDetails.tsx
src/store/wallet/effects/send/send.ts
src/store/wallet/wallet.models.ts

With this refactor I intend to use the same error messages for users as those shown in the "general send". For example those used for the "Insufficient funds for fee" case, taking the user to the "Buy crypto" flow if they do not have enough funds to cover the miners' fee.
Also we will be able to better identify the causes of createTx error in our analytics.
And I also fixed some type errors.

Ref: sell/swap insufficient funds for fee error

---

patches/redux-persist-transform-encrypt+3.0.1.patch
src/store/index.ts
src/store/rate/rate.reducer.ts
src/store/shop/shop.reducer.ts
src/store/wallet/effects/init/init.ts

Adds the `RATE` store to the list of `unencryptedStores` since rates are not sensitive and do not require encryption, which can lead to performance issues on older devices.

Perf: add ability to specify unencrypted stores to boost perfomance

---

src/navigation/tabs/shop/ShopHome.tsx
src/navigation/tabs/shop/gift-card/GiftCardDeeplink.tsx
src/navigation/wallet/screens/AccountDetails.tsx
src/navigation/wallet/screens/WalletDetails.tsx
src/store/app/app.effects.ts
src/store/index.ts
src/store/shop-catalog/index.ts
src/store/shop-catalog/shop-catalog.actions.ts
src/store/shop-catalog/shop-catalog.models.ts
src/store/shop-catalog/shop-catalog.reducer.ts
src/store/shop-catalog/shop-catalog.selectors.ts
src/store/shop-catalog/shop-catalog.types.ts
src/store/shop/shop.actions.ts
src/store/shop/shop.effects.ts
src/store/shop/shop.reducer.ts
src/store/shop/shop.selectors.ts
src/store/shop/shop.types.ts

Shop catalog data is large and doesn't require encryption, so this PR moves it out of the encrypted `SHOP` store to the new unencrypted `SHOP_CATALOG` store to boost performance, while keeping the remaining data in the `SHOP` store encrypted.

Perf: migrate shop catalog data from `SHOP` to `SHOP_CATALOG`

---

src/components/list/KeyWalletsRow.tsx

```
TypeError: Cannot read property 'map' of undefined
This error is located at:
in KeyWalletsRow (created by WalletSelector)
```

Fix: avoid typeError when mergeUtxoAndEvmAccounts is undefined

---

ios/Podfile.lock
package.json
yarn.lock

Downgrades react-native-screens to `3.35.0`.

Fix: headerRight height rendering on android 

---

src/navigation/wallet/WalletGroup.tsx
src/navigation/wallet/components/PaymentSent.tsx
src/navigation/wallet/screens/send/confirm/Confirm.tsx

* Disable gestures on all Confirm Screens
* Revert back to `react-native` plugin for TouchableOpacity on PaymentSent screen
* Normal confirm requires an extra padding on Android devices

Fix: Slide button and PaymentSent screen

---

src/navigation/services/buy-crypto/utils/moonpay-utils.ts

>Luke Kennedy (From MoonPay team): Maximum Buy Limit - Looks like the maximum buy is hardcoded to $20,000. Those who want to put large transactions through would be happy to know that we support transaction sizes up to $30,000; it could be worth somehow indicating this to users for the MoonPay option in your upstream UI.

Ref: new max limits for Moonpay-buy

---

ios/Podfile.lock
package.json
src/components/modal/ongoing-process/OngoingProcess.tsx
yarn.lock

Fixes sporadic SVG related crash on iOS when navigating to buy/swap/sell by upgrading `react-native-svg` to 15.11.2. Also improves setTimeout handling in the ongoing process component.

Fix: svg crash on iOS when navigating to buy/swap/sell 

---

src/components/base/TouchableOpacity.tsx
src/components/button/Button.tsx
src/components/modal/wallet-connect/WalletConnectStartModal.tsx
src/navigation/wallet-connect/screens/WalletConnectConnections.tsx

Currently, TouchableOpacity pressability inside of a sheet modal only works on android if it is imported from react-native, whereas TouchableOpacity inside of a header only works if it is imported from react-native-gesture-handler. This PR adds a new optional `touchableLibrary` param to the custom TouchableOpacity component that makes it possible to configure the import paths of TouchableOpacity components appropriately based on where they are placed to ensure onPress handlers fire on android.

Fix: wallet connect pressables on android

---

src/navigation/coinbase/components/CoinbaseDashboard.tsx

Error: 
```
[Info] coinbaseDisconnectAccount: success
console.js:589 Warning: TypeError: Cannot read property 'length' of null
This error is located at:
in FlashList (created by CoinbaseDashboard)
in RCTView (created by View)
in View
in StyledNativeComponent (created by Styled(View))
in Styled(View) (created by CoinbaseDashboard)
in CoinbaseDashboard (created by CoinbaseRoot)
in CoinbaseRoot (created by SceneView)
in StaticContainer
in EnsureSingleNavigator (created by SceneView)
in SceneView (created by SceneView)
in RCTView (created by View)
in View (created by DebugContainer)
in DebugContainer (created by MaybeNestedStack)
in MaybeNestedStack (created by SceneView)
``` 
Source: https://github.com/Shopify/flash-list/issues/954

Fix: disconnecting Coinbase crashes the app (Android)

---

src/constants/currencies.ts

When sending testnet4 BCH to multiple recipients, the transaction proposal screen currently displays an `undefined` address prefix for each receiving address. This PR ensures the prefix shows as `bchtest`.

Fix: undefined testnet4 BCH prefix

---

src/components/list/KeyWalletsRow.tsx
src/navigation/bitpay-id/screens/ReceiveSettings.tsx
src/navigation/wallet/screens/GlobalSelect.tsx
src/navigation/wallet/screens/send/confirm/Shared.tsx
src/store/wallet/utils/wallet.ts

This PR fixes an issue that led to a "No compatible wallets" error when trying to select a wallet in BitPay ID receive settings.

Fix: BitPay ID receive settings

---

src/navigation/coinbase/screens/CoinbaseAccount.tsx
src/navigation/services/buy-crypto/screens/BuyCryptoRoot.tsx
src/navigation/services/swap-crypto/screens/SwapCryptoRoot.tsx

Prevent encrypt pass prompt for external services if token is created with associatedWallet. Otherwise BWC requieres the encrypt, to be able to create the wallet with the same mnemonics.

Fix: prevent encrypt pass prompt for tokens in external services

---

src/navigation/wallet/screens/SendToOptions.tsx

Currently, the native keyboard stays open and blocks the numpad in the amount modal after an address is pasted into the search input of the "Transfer to multiple recipients" flow. The native keyboard also cannot be dismissed by tapping elsewhere on the screen. This PR hides the native keyboard right before the amount modal is shown.

Fix: prevent keyboard from blocking numpad when sending to multiple addresses

---

src/navigation/wallet/screens/AccountDetails.tsx

Currently, the onPress handler of the settings header button in account details is not firing on android. This PR ensures the settings header button is useable on android.

Fix: account details settings icon press handling on android

---

src/components/modal/bottom-notification/BottomNotification.tsx
src/navigation/tabs/shop/bill/screens/ConnectBillsOptions.tsx
src/navigation/tabs/shop/components/Bills.tsx
src/navigation/tabs/shop/gift-card/screens/GiftCardDetails.tsx

Uses the react-native-modal library for bottom sheet notifications that contain scrollable content to fix an issue where these notifications don't scroll on android, such as in the bill pay user info confirmation sheet and gift card redeem instructions.

Fix: scrollable bottom sheet notifications on android

---

src/navigation/tabs/shop/gift-card/screens/BuyGiftCard.tsx

If a gift card already has "Gift Card" in the name, remove it in the header title of BuyGiftCard.tsx to prevent a situation where the header title says "Buy Example Gift Card Gift Card."

Fix: prevent double "Gift Card" text in header title

---

src/navigation/bitpay-id/utils/bitpay-id-utils.ts
src/navigation/services/swap-crypto/screens/SwapCryptoRoot.tsx
src/navigation/services/swap-crypto/styled/SwapCryptoRoot.styled.tsx
src/navigation/wallet/screens/TransactionProposalNotifications.tsx

- Fix for the issue where the "Select Destination Wallet" button remains "disabled" despite being enabled.
- Fix for the names of the selected wallets/coins. Currently, they only show the icon.

Fix: UI for wallet selectors in swapRoot

---

src/components/modal/wallet-connect/WalletConnectStartModal.tsx
src/navigation/services/buy-crypto/components/terms/MoonpayTerms.tsx
src/navigation/services/buy-crypto/components/terms/RampTerms.tsx
src/navigation/services/buy-crypto/components/terms/SardineTerms.tsx
src/navigation/services/buy-crypto/components/terms/SimplexTerms.tsx
src/navigation/services/buy-crypto/components/terms/TransakTerms.tsx
src/navigation/services/buy-crypto/components/terms/banxaTerms.tsx

Currently, the "Read More" and "Terms of Service" links in the Buy Crypto offers are no longer clickable. This PR fixes it.

Fix: buy crypto terms of services links

---

src/components/modal/in-app-notification/InAppNotification.tsx
src/navigation/wallet-connect/constants/abis/abi-invoice.ts
src/navigation/wallet-connect/constants/abis/index.ts
src/navigation/wallet-connect/screens/WalletConnectConfirm.tsx
src/navigation/wallet-connect/screens/WalletConnectHome.tsx
src/store/wallet-connect-v2/wallet-connect-v2.effects.ts
src/store/wallet/effects/amount/amount.ts
src/store/wallet/effects/send/send.ts
src/store/wallet/wallet.models.ts
src/utils/helper-methods.ts

We have more control over potential errors: nonce, insufficient funds, etc. by using Bitcore
Fixes custom data information to show WC icon on sent transactions.
Fixes handling other errors than insufficient funds correctly.
Handle auto approval errors correctly.
Decode the data using invoice abi in order to be able to display amount values

[REF] use bws for sending wc transactions

---

src/store/wallet/effects/init/init.ts

* Show Exchange Rates at Home when install the app from scratch.

Fix: get rates when app is installed for first time

---

package.json
src/store/index.ts
src/store/transforms/encrypt.ts
src/store/transforms/transforms.ts
yarn.lock

Moves `WALLET` store to `unencryptedStores`, and adds a new redux-persist transform that encrypts only sensitive `WALLET` fields before persisting the `WALLET` state. This greatly reduces encryption/decryption time, which boosts overall app performance, especially on older devices.

Perf: only encrypt sensitive wallet store fields to improve performance

---

src/store/index.ts
src/store/shop/shop.effects.ts
src/store/transforms/encrypt.ts
src/store/transforms/transforms.ts

Moves `APP` and `SHOP` stores to `unencryptedStores` and updates the `encryptSpecificFields` transform to only encrypt `APP.identity.priv` and sensitive `SHOP` store fields to reduce encryption/decryption time. Also ensures that gift card invoice objects are never persisted to the store as they are not used anywhere in the current codebase.

Perf: only encrypt sensitive APP and SHOP store fields to boost performance

---

src/navigation/wallet/screens/PriceCharts.tsx
src/store/rate/rate.actions.ts
src/store/rate/rate.reducer.ts
src/store/rate/rate.types.ts
src/store/wallet/effects/rates/rates.ts

This PR should also correct an inconsistency between the chart and the selected fiat currency.
Without this fix, if you change the fiat currency in settings and go to the charts before the cached time expires, it will display the current value correctly but the chart of the previously selected fiat currency.

Fix: checks for price charts and fiatCurrency in rate cache

---

src/navigation/onboarding/components/TermsBox.tsx

Temporary workaround on older android devices for a press handling issue that occurs when a pressable checkbox element group contains nested links that are themselves pressable and have their own onPress handlers, such as the `Wallet Terms of Use` link. This workaround will no longer be needed once https://github.com/bitpay/bitpay-app/pull/1712 is merged.

Fix: ensure terms checkbox is pressable on all devices

---

src/components/chain-search/ChainSearch.tsx
src/navigation/wallet/WalletGroup.tsx
src/navigation/wallet/screens/AccountDetails.tsx
src/navigation/wallet/screens/AccountSettings.tsx
src/navigation/wallet/screens/KeySettings.tsx

- Fix: show gear with simplified redirection to Account Settings instead of 3 dots with list of options for SVM Accounts
- Ref: do not show chain selector in the Search bar for SVM Accounts

Fix: UI adjustments for SVM Accounts

---

src/store/scan/scan.effects.ts
src/store/wallet/utils/validations.ts

This PR fixes the following issues:
1. When scanning an invoice that has a `buyerEmailAddress` set, the user will now skip the "Enter Email" screen and go directly to the confirm screen.
2. Scanning or pasting a BIP21 URI from within a wallet will no longer result in a currency/network mismatch error.

Fix: misc invoice payment bugs

---

src/navigation/auth/screens/Login.tsx

This PR fixes an issue that caused an "email required" error to appear when logging in after using a password manager to autofill the login form despite the email input containing the autofilled email.

Fix: ensure login works smoothly with password managers

---

src/constants/WalletConnectV2.tsx

TODO: In order to support link mode, the universal link must be added to the cloud project configuration.

[FEAT] link mode support

---

src/navigation/wallet/screens/wallet-settings/ExportTransactionHistory.tsx
src/store/wallet/effects/transactions/transactions.ts

- replace ongoingProcess with button state handling
- ensure that the full history is fetched for the CSV export.
- remove the destination address from the CSV, since most transactions have multiple outputs and it makes no sense to show only the first one. I keep the Tag: `Destination`. But now I show: Sent / Received 
- I removed a log that provided little information and slowed down performance.
- skip the TXProcess since it's not needed for the CSV in particular, and it slowed down performance.

[REF] improve export tx history performance
